#define MATSYM_10k 0xe951
#define MATSYM_10mp 0xe952
#define MATSYM_11mp 0xe953
#define MATSYM_123 0xeb8d
#define MATSYM_12mp 0xe954
#define MATSYM_13mp 0xe955
#define MATSYM_14mp 0xe956
#define MATSYM_15mp 0xe957
#define MATSYM_16mp 0xe958
#define MATSYM_17mp 0xe959
#define MATSYM_18_up_rating 0xf8fd
#define MATSYM_18mp 0xe95a
#define MATSYM_19mp 0xe95b
#define MATSYM_1k 0xe95c
#define MATSYM_1k_plus 0xe95d
#define MATSYM_1x_mobiledata 0xefcd
#define MATSYM_20mp 0xe95e
#define MATSYM_21mp 0xe95f
#define MATSYM_22mp 0xe960
#define MATSYM_23mp 0xe961
#define MATSYM_24mp 0xe962
#define MATSYM_2k 0xe963
#define MATSYM_2k_plus 0xe964
#define MATSYM_2mp 0xe965
#define MATSYM_30fps 0xefce
#define MATSYM_30fps_select 0xefcf
#define MATSYM_360 0xe577
#define MATSYM_3d_rotation 0xe84d
#define MATSYM_3g_mobiledata 0xefd0
#define MATSYM_3k 0xe966
#define MATSYM_3k_plus 0xe967
#define MATSYM_3mp 0xe968
#define MATSYM_3p 0xefd1
#define MATSYM_4g_mobiledata 0xefd2
#define MATSYM_4g_plus_mobiledata 0xefd3
#define MATSYM_4k 0xe072
#define MATSYM_4k_plus 0xe969
#define MATSYM_4mp 0xe96a
#define MATSYM_5g 0xef38
#define MATSYM_5k 0xe96b
#define MATSYM_5k_plus 0xe96c
#define MATSYM_5mp 0xe96d
#define MATSYM_60fps 0xefd4
#define MATSYM_60fps_select 0xefd5
#define MATSYM_6_ft_apart 0xf21e
#define MATSYM_6k 0xe96e
#define MATSYM_6k_plus 0xe96f
#define MATSYM_6mp 0xe970
#define MATSYM_7k 0xe971
#define MATSYM_7k_plus 0xe972
#define MATSYM_7mp 0xe973
#define MATSYM_8k 0xe974
#define MATSYM_8k_plus 0xe975
#define MATSYM_8mp 0xe976
#define MATSYM_9k 0xe977
#define MATSYM_9k_plus 0xe978
#define MATSYM_9mp 0xe979
#define MATSYM_abc 0xeb94
#define MATSYM_ac_unit 0xeb3b
#define MATSYM_access_alarm 0xe190
#define MATSYM_access_alarms 0xe191
#define MATSYM_access_time 0xe192
#define MATSYM_access_time_filled 0xefd6
#define MATSYM_accessibility 0xe84e
#define MATSYM_accessibility_new 0xe92c
#define MATSYM_accessible 0xe914
#define MATSYM_accessible_forward 0xe934
#define MATSYM_account_balance 0xe84f
#define MATSYM_account_balance_wallet 0xe850
#define MATSYM_account_box 0xe851
#define MATSYM_account_circle 0xe853
#define MATSYM_account_tree 0xe97a
#define MATSYM_ad_units 0xef39
#define MATSYM_adb 0xe60e
#define MATSYM_add 0xe145
#define MATSYM_add_a_photo 0xe439
#define MATSYM_add_alarm 0xe193
#define MATSYM_add_alert 0xe003
#define MATSYM_add_box 0xe146
#define MATSYM_add_business 0xe729
#define MATSYM_add_call 0xe0e8
#define MATSYM_add_card 0xeb86
#define MATSYM_add_chart 0xe97b
#define MATSYM_add_circle 0xe147
#define MATSYM_add_circle_outline 0xe148
#define MATSYM_add_comment 0xe266
#define MATSYM_add_home 0xf8eb
#define MATSYM_add_home_work 0xf8ed
#define MATSYM_add_ic_call 0xe97c
#define MATSYM_add_link 0xe178
#define MATSYM_add_location 0xe567
#define MATSYM_add_location_alt 0xef3a
#define MATSYM_add_moderator 0xe97d
#define MATSYM_add_photo_alternate 0xe43e
#define MATSYM_add_reaction 0xe1d3
#define MATSYM_add_road 0xef3b
#define MATSYM_add_shopping_cart 0xe854
#define MATSYM_add_task 0xf23a
#define MATSYM_add_to_drive 0xe65c
#define MATSYM_add_to_home_screen 0xe1fe
#define MATSYM_add_to_photos 0xe39d
#define MATSYM_add_to_queue 0xe05c
#define MATSYM_addchart 0xef3c
#define MATSYM_adf_scanner 0xeada
#define MATSYM_adjust 0xe39e
#define MATSYM_admin_panel_settings 0xef3d
#define MATSYM_adobe 0xea96
#define MATSYM_ads_click 0xe762
#define MATSYM_agriculture 0xea79
#define MATSYM_air 0xefd8
#define MATSYM_airline_seat_flat 0xe630
#define MATSYM_airline_seat_flat_angled 0xe631
#define MATSYM_airline_seat_individual_suite 0xe632
#define MATSYM_airline_seat_legroom_extra 0xe633
#define MATSYM_airline_seat_legroom_normal 0xe634
#define MATSYM_airline_seat_legroom_reduced 0xe635
#define MATSYM_airline_seat_recline_extra 0xe636
#define MATSYM_airline_seat_recline_normal 0xe637
#define MATSYM_airline_stops 0xe7d0
#define MATSYM_airlines 0xe7ca
#define MATSYM_airplane_ticket 0xefd9
#define MATSYM_airplanemode_active 0xe195
#define MATSYM_airplanemode_inactive 0xe194
#define MATSYM_airplanemode_off 0xe194
#define MATSYM_airplanemode_on 0xe195
#define MATSYM_airplay 0xe055
#define MATSYM_airport_shuttle 0xeb3c
#define MATSYM_alarm 0xe855
#define MATSYM_alarm_add 0xe856
#define MATSYM_alarm_off 0xe857
#define MATSYM_alarm_on 0xe858
#define MATSYM_album 0xe019
#define MATSYM_align_horizontal_center 0xe00f
#define MATSYM_align_horizontal_left 0xe00d
#define MATSYM_align_horizontal_right 0xe010
#define MATSYM_align_vertical_bottom 0xe015
#define MATSYM_align_vertical_center 0xe011
#define MATSYM_align_vertical_top 0xe00c
#define MATSYM_all_inbox 0xe97f
#define MATSYM_all_inclusive 0xeb3d
#define MATSYM_all_out 0xe90b
#define MATSYM_alt_route 0xf184
#define MATSYM_alternate_email 0xe0e6
#define MATSYM_amp_stories 0xea13
#define MATSYM_analytics 0xef3e
#define MATSYM_anchor 0xf1cd
#define MATSYM_android 0xe859
#define MATSYM_animation 0xe71c
#define MATSYM_announcement 0xe85a
#define MATSYM_aod 0xefda
#define MATSYM_apartment 0xea40
#define MATSYM_api 0xf1b7
#define MATSYM_app_blocking 0xef3f
#define MATSYM_app_registration 0xef40
#define MATSYM_app_settings_alt 0xef41
#define MATSYM_app_shortcut 0xeae4
#define MATSYM_apple 0xea80
#define MATSYM_approval 0xe982
#define MATSYM_apps 0xe5c3
#define MATSYM_apps_outage 0xe7cc
#define MATSYM_architecture 0xea3b
#define MATSYM_archive 0xe149
#define MATSYM_area_chart 0xe770
#define MATSYM_arrow_back 0xe5c4
#define MATSYM_arrow_back_ios 0xe5e0
#define MATSYM_arrow_back_ios_new 0xe2ea
#define MATSYM_arrow_circle_down 0xf181
#define MATSYM_arrow_circle_left 0xeaa7
#define MATSYM_arrow_circle_right 0xeaaa
#define MATSYM_arrow_circle_up 0xf182
#define MATSYM_arrow_downward 0xe5db
#define MATSYM_arrow_drop_down 0xe5c5
#define MATSYM_arrow_drop_down_circle 0xe5c6
#define MATSYM_arrow_drop_up 0xe5c7
#define MATSYM_arrow_forward 0xe5c8
#define MATSYM_arrow_forward_ios 0xe5e1
#define MATSYM_arrow_left 0xe5de
#define MATSYM_arrow_outward 0xf8ce
#define MATSYM_arrow_right 0xe5df
#define MATSYM_arrow_right_alt 0xe941
#define MATSYM_arrow_upward 0xe5d8
#define MATSYM_art_track 0xe060
#define MATSYM_article 0xef42
#define MATSYM_aspect_ratio 0xe85b
#define MATSYM_assessment 0xe85c
#define MATSYM_assignment 0xe85d
#define MATSYM_assignment_add 0xf848
#define MATSYM_assignment_ind 0xe85e
#define MATSYM_assignment_late 0xe85f
#define MATSYM_assignment_return 0xe860
#define MATSYM_assignment_returned 0xe861
#define MATSYM_assignment_turned_in 0xe862
#define MATSYM_assist_walker 0xf8d5
#define MATSYM_assistant 0xe39f
#define MATSYM_assistant_direction 0xe988
#define MATSYM_assistant_navigation 0xe989
#define MATSYM_assistant_photo 0xe3a0
#define MATSYM_assured_workload 0xeb6f
#define MATSYM_atm 0xe573
#define MATSYM_attach_email 0xea5e
#define MATSYM_attach_file 0xe226
#define MATSYM_attach_money 0xe227
#define MATSYM_attachment 0xe2bc
#define MATSYM_attractions 0xea52
#define MATSYM_attribution 0xefdb
#define MATSYM_audio_file 0xeb82
#define MATSYM_audiotrack 0xe3a1
#define MATSYM_auto_awesome 0xe65f
#define MATSYM_auto_awesome_mosaic 0xe660
#define MATSYM_auto_awesome_motion 0xe661
#define MATSYM_auto_delete 0xea4c
#define MATSYM_auto_fix_high 0xe663
#define MATSYM_auto_fix_normal 0xe664
#define MATSYM_auto_fix_off 0xe665
#define MATSYM_auto_graph 0xe4fb
#define MATSYM_auto_mode 0xec20
#define MATSYM_auto_stories 0xe666
#define MATSYM_autofps_select 0xefdc
#define MATSYM_autorenew 0xe863
#define MATSYM_av_timer 0xe01b
#define MATSYM_baby_changing_station 0xf19b
#define MATSYM_back_hand 0xe764
#define MATSYM_backpack 0xf19c
#define MATSYM_backspace 0xe14a
#define MATSYM_backup 0xe864
#define MATSYM_backup_table 0xef43
#define MATSYM_badge 0xea67
#define MATSYM_bakery_dining 0xea53
#define MATSYM_balance 0xeaf6
#define MATSYM_balcony 0xe58f
#define MATSYM_ballot 0xe172
#define MATSYM_bar_chart 0xe26b
#define MATSYM_barcode_reader 0xf85c
#define MATSYM_batch_prediction 0xf0f5
#define MATSYM_bathroom 0xefdd
#define MATSYM_bathtub 0xea41
#define MATSYM_battery_0_bar 0xebdc
#define MATSYM_battery_1_bar 0xebd9
#define MATSYM_battery_2_bar 0xebe0
#define MATSYM_battery_3_bar 0xebdd
#define MATSYM_battery_4_bar 0xebe2
#define MATSYM_battery_5_bar 0xebd4
#define MATSYM_battery_6_bar 0xebd2
#define MATSYM_battery_alert 0xe19c
#define MATSYM_battery_charging_full 0xe1a3
#define MATSYM_battery_full 0xe1a4
#define MATSYM_battery_saver 0xefde
#define MATSYM_battery_std 0xe1a5
#define MATSYM_battery_unknown 0xe1a6
#define MATSYM_beach_access 0xeb3e
#define MATSYM_bed 0xefdf
#define MATSYM_bedroom_baby 0xefe0
#define MATSYM_bedroom_child 0xefe1
#define MATSYM_bedroom_parent 0xefe2
#define MATSYM_bedtime 0xef44
#define MATSYM_bedtime_off 0xeb76
#define MATSYM_beenhere 0xe52d
#define MATSYM_bento 0xf1f4
#define MATSYM_bike_scooter 0xef45
#define MATSYM_biotech 0xea3a
#define MATSYM_blender 0xefe3
#define MATSYM_blind 0xf8d6
#define MATSYM_blinds 0xe286
#define MATSYM_blinds_closed 0xec1f
#define MATSYM_block 0xe14b
#define MATSYM_block_flipped 0xef46
#define MATSYM_bloodtype 0xefe4
#define MATSYM_bluetooth 0xe1a7
#define MATSYM_bluetooth_audio 0xe60f
#define MATSYM_bluetooth_connected 0xe1a8
#define MATSYM_bluetooth_disabled 0xe1a9
#define MATSYM_bluetooth_drive 0xefe5
#define MATSYM_bluetooth_searching 0xe1aa
#define MATSYM_blur_circular 0xe3a2
#define MATSYM_blur_linear 0xe3a3
#define MATSYM_blur_off 0xe3a4
#define MATSYM_blur_on 0xe3a5
#define MATSYM_bolt 0xea0b
#define MATSYM_book 0xe865
#define MATSYM_book_online 0xf217
#define MATSYM_bookmark 0xe866
#define MATSYM_bookmark_add 0xe598
#define MATSYM_bookmark_added 0xe599
#define MATSYM_bookmark_border 0xe867
#define MATSYM_bookmark_outline 0xe867
#define MATSYM_bookmark_remove 0xe59a
#define MATSYM_bookmarks 0xe98b
#define MATSYM_border_all 0xe228
#define MATSYM_border_bottom 0xe229
#define MATSYM_border_clear 0xe22a
#define MATSYM_border_color 0xe22b
#define MATSYM_border_horizontal 0xe22c
#define MATSYM_border_inner 0xe22d
#define MATSYM_border_left 0xe22e
#define MATSYM_border_outer 0xe22f
#define MATSYM_border_right 0xe230
#define MATSYM_border_style 0xe231
#define MATSYM_border_top 0xe232
#define MATSYM_border_vertical 0xe233
#define MATSYM_boy 0xeb67
#define MATSYM_branding_watermark 0xe06b
#define MATSYM_breakfast_dining 0xea54
#define MATSYM_brightness_1 0xe3a6
#define MATSYM_brightness_2 0xe3a7
#define MATSYM_brightness_3 0xe3a8
#define MATSYM_brightness_4 0xe3a9
#define MATSYM_brightness_5 0xe3aa
#define MATSYM_brightness_6 0xe3ab
#define MATSYM_brightness_7 0xe3ac
#define MATSYM_brightness_auto 0xe1ab
#define MATSYM_brightness_high 0xe1ac
#define MATSYM_brightness_low 0xe1ad
#define MATSYM_brightness_medium 0xe1ae
#define MATSYM_broadcast_on_home 0xf8f8
#define MATSYM_broadcast_on_personal 0xf8f9
#define MATSYM_broken_image 0xe3ad
#define MATSYM_browse_gallery 0xebd1
#define MATSYM_browser_not_supported 0xef47
#define MATSYM_browser_updated 0xe7cf
#define MATSYM_brunch_dining 0xea73
#define MATSYM_brush 0xe3ae
#define MATSYM_bubble_chart 0xe6dd
#define MATSYM_bug_report 0xe868
#define MATSYM_build 0xe869
#define MATSYM_build_circle 0xef48
#define MATSYM_bungalow 0xe591
#define MATSYM_burst_mode 0xe43c
#define MATSYM_bus_alert 0xe98f
#define MATSYM_business 0xe0af
#define MATSYM_business_center 0xeb3f
#define MATSYM_cabin 0xe589
#define MATSYM_cable 0xefe6
#define MATSYM_cached 0xe86a
#define MATSYM_cake 0xe7e9
#define MATSYM_calculate 0xea5f
#define MATSYM_calendar_month 0xebcc
#define MATSYM_calendar_today 0xe935
#define MATSYM_calendar_view_day 0xe936
#define MATSYM_calendar_view_month 0xefe7
#define MATSYM_calendar_view_week 0xefe8
#define MATSYM_call 0xe0b0
#define MATSYM_call_end 0xe0b1
#define MATSYM_call_made 0xe0b2
#define MATSYM_call_merge 0xe0b3
#define MATSYM_call_missed 0xe0b4
#define MATSYM_call_missed_outgoing 0xe0e4
#define MATSYM_call_received 0xe0b5
#define MATSYM_call_split 0xe0b6
#define MATSYM_call_to_action 0xe06c
#define MATSYM_camera 0xe3af
#define MATSYM_camera_alt 0xe3b0
#define MATSYM_camera_enhance 0xe8fc
#define MATSYM_camera_front 0xe3b1
#define MATSYM_camera_indoor 0xefe9
#define MATSYM_camera_outdoor 0xefea
#define MATSYM_camera_rear 0xe3b2
#define MATSYM_camera_roll 0xe3b3
#define MATSYM_cameraswitch 0xefeb
#define MATSYM_campaign 0xef49
#define MATSYM_cancel 0xe5c9
#define MATSYM_cancel_presentation 0xe0e9
#define MATSYM_cancel_schedule_send 0xea39
#define MATSYM_candlestick_chart 0xead4
#define MATSYM_car_crash 0xebf2
#define MATSYM_car_rental 0xea55
#define MATSYM_car_repair 0xea56
#define MATSYM_card_giftcard 0xe8f6
#define MATSYM_card_membership 0xe8f7
#define MATSYM_card_travel 0xe8f8
#define MATSYM_carpenter 0xf1f8
#define MATSYM_cases 0xe992
#define MATSYM_casino 0xeb40
#define MATSYM_cast 0xe307
#define MATSYM_cast_connected 0xe308
#define MATSYM_cast_for_education 0xefec
#define MATSYM_castle 0xeab1
#define MATSYM_catching_pokemon 0xe508
#define MATSYM_category 0xe574
#define MATSYM_celebration 0xea65
#define MATSYM_cell_tower 0xebba
#define MATSYM_cell_wifi 0xe0ec
#define MATSYM_center_focus_strong 0xe3b4
#define MATSYM_center_focus_weak 0xe3b5
#define MATSYM_chair 0xefed
#define MATSYM_chair_alt 0xefee
#define MATSYM_chalet 0xe585
#define MATSYM_change_circle 0xe2e7
#define MATSYM_change_history 0xe86b
#define MATSYM_charging_station 0xf19d
#define MATSYM_chat 0xe0b7
#define MATSYM_chat_bubble 0xe0ca
#define MATSYM_chat_bubble_outline 0xe0cb
#define MATSYM_check 0xe5ca
#define MATSYM_check_box 0xe834
#define MATSYM_check_box_outline_blank 0xe835
#define MATSYM_check_circle 0xe86c
#define MATSYM_check_circle_outline 0xe92d
#define MATSYM_checklist 0xe6b1
#define MATSYM_checklist_rtl 0xe6b3
#define MATSYM_checkroom 0xf19e
#define MATSYM_chevron_left 0xe5cb
#define MATSYM_chevron_right 0xe5cc
#define MATSYM_child_care 0xeb41
#define MATSYM_child_friendly 0xeb42
#define MATSYM_chrome_reader_mode 0xe86d
#define MATSYM_church 0xeaae
#define MATSYM_circle 0xef4a
#define MATSYM_circle_notifications 0xe994
#define MATSYM_class 0xe86e
#define MATSYM_clean_hands 0xf21f
#define MATSYM_cleaning_services 0xf0ff
#define MATSYM_clear 0xe14c
#define MATSYM_clear_all 0xe0b8
#define MATSYM_close 0xe5cd
#define MATSYM_close_fullscreen 0xf1cf
#define MATSYM_closed_caption 0xe01c
#define MATSYM_closed_caption_disabled 0xf1dc
#define MATSYM_closed_caption_off 0xe996
#define MATSYM_cloud 0xe2bd
#define MATSYM_cloud_circle 0xe2be
#define MATSYM_cloud_done 0xe2bf
#define MATSYM_cloud_download 0xe2c0
#define MATSYM_cloud_off 0xe2c1
#define MATSYM_cloud_queue 0xe2c2
#define MATSYM_cloud_sync 0xeb5a
#define MATSYM_cloud_upload 0xe2c3
#define MATSYM_cloudy_snowing 0xe810
#define MATSYM_co2 0xe7b0
#define MATSYM_co_present 0xeaf0
#define MATSYM_code 0xe86f
#define MATSYM_code_off 0xe4f3
#define MATSYM_coffee 0xefef
#define MATSYM_coffee_maker 0xeff0
#define MATSYM_collections 0xe3b6
#define MATSYM_collections_bookmark 0xe431
#define MATSYM_color_lens 0xe3b7
#define MATSYM_colorize 0xe3b8
#define MATSYM_comment 0xe0b9
#define MATSYM_comment_bank 0xea4e
#define MATSYM_comments_disabled 0xe7a2
#define MATSYM_commit 0xeaf5
#define MATSYM_commute 0xe940
#define MATSYM_compare 0xe3b9
#define MATSYM_compare_arrows 0xe915
#define MATSYM_compass_calibration 0xe57c
#define MATSYM_compost 0xe761
#define MATSYM_compress 0xe94d
#define MATSYM_computer 0xe30a
#define MATSYM_confirmation_num 0xe638
#define MATSYM_confirmation_number 0xe638
#define MATSYM_connect_without_contact 0xf223
#define MATSYM_connected_tv 0xe998
#define MATSYM_connecting_airports 0xe7c9
#define MATSYM_construction 0xea3c
#define MATSYM_contact_emergency 0xf8d1
#define MATSYM_contact_mail 0xe0d0
#define MATSYM_contact_page 0xf22e
#define MATSYM_contact_phone 0xe0cf
#define MATSYM_contact_support 0xe94c
#define MATSYM_contactless 0xea71
#define MATSYM_contacts 0xe0ba
#define MATSYM_content_copy 0xe14d
#define MATSYM_content_cut 0xe14e
#define MATSYM_content_paste 0xe14f
#define MATSYM_content_paste_go 0xea8e
#define MATSYM_content_paste_off 0xe4f8
#define MATSYM_content_paste_search 0xea9b
#define MATSYM_contrast 0xeb37
#define MATSYM_control_camera 0xe074
#define MATSYM_control_point 0xe3ba
#define MATSYM_control_point_duplicate 0xe3bb
#define MATSYM_conveyor_belt 0xf867
#define MATSYM_cookie 0xeaac
#define MATSYM_copy_all 0xe2ec
#define MATSYM_copyright 0xe90c
#define MATSYM_coronavirus 0xf221
#define MATSYM_corporate_fare 0xf1d0
#define MATSYM_cottage 0xe587
#define MATSYM_countertops 0xf1f7
#define MATSYM_create 0xe150
#define MATSYM_create_new_folder 0xe2cc
#define MATSYM_credit_card 0xe870
#define MATSYM_credit_card_off 0xe4f4
#define MATSYM_credit_score 0xeff1
#define MATSYM_crib 0xe588
#define MATSYM_crisis_alert 0xebe9
#define MATSYM_crop 0xe3be
#define MATSYM_crop_16_9 0xe3bc
#define MATSYM_crop_3_2 0xe3bd
#define MATSYM_crop_5_4 0xe3bf
#define MATSYM_crop_7_5 0xe3c0
#define MATSYM_crop_din 0xe3c1
#define MATSYM_crop_free 0xe3c2
#define MATSYM_crop_landscape 0xe3c3
#define MATSYM_crop_original 0xe3c4
#define MATSYM_crop_portrait 0xe3c5
#define MATSYM_crop_rotate 0xe437
#define MATSYM_crop_square 0xe3c6
#define MATSYM_cruelty_free 0xe799
#define MATSYM_css 0xeb93
#define MATSYM_currency_bitcoin 0xebc5
#define MATSYM_currency_exchange 0xeb70
#define MATSYM_currency_franc 0xeafa
#define MATSYM_currency_lira 0xeaef
#define MATSYM_currency_pound 0xeaf1
#define MATSYM_currency_ruble 0xeaec
#define MATSYM_currency_rupee 0xeaf7
#define MATSYM_currency_yen 0xeafb
#define MATSYM_currency_yuan 0xeaf9
#define MATSYM_curtains 0xec1e
#define MATSYM_curtains_closed 0xec1d
#define MATSYM_cyclone 0xebd5
#define MATSYM_dangerous 0xe99a
#define MATSYM_dark_mode 0xe51c
#define MATSYM_dashboard 0xe871
#define MATSYM_dashboard_customize 0xe99b
#define MATSYM_data_array 0xead1
#define MATSYM_data_exploration 0xe76f
#define MATSYM_data_object 0xead3
#define MATSYM_data_saver_off 0xeff2
#define MATSYM_data_saver_on 0xeff3
#define MATSYM_data_thresholding 0xeb9f
#define MATSYM_data_usage 0xe1af
#define MATSYM_dataset 0xf8ee
#define MATSYM_dataset_linked 0xf8ef
#define MATSYM_date_range 0xe916
#define MATSYM_deblur 0xeb77
#define MATSYM_deck 0xea42
#define MATSYM_dehaze 0xe3c7
#define MATSYM_delete 0xe872
#define MATSYM_delete_forever 0xe92b
#define MATSYM_delete_outline 0xe92e
#define MATSYM_delete_sweep 0xe16c
#define MATSYM_delivery_dining 0xea72
#define MATSYM_density_large 0xeba9
#define MATSYM_density_medium 0xeb9e
#define MATSYM_density_small 0xeba8
#define MATSYM_departure_board 0xe576
#define MATSYM_description 0xe873
#define MATSYM_deselect 0xebb6
#define MATSYM_design_services 0xf10a
#define MATSYM_desk 0xf8f4
#define MATSYM_desktop_access_disabled 0xe99d
#define MATSYM_desktop_mac 0xe30b
#define MATSYM_desktop_windows 0xe30c
#define MATSYM_details 0xe3c8
#define MATSYM_developer_board 0xe30d
#define MATSYM_developer_board_off 0xe4ff
#define MATSYM_developer_mode 0xe1b0
#define MATSYM_device_hub 0xe335
#define MATSYM_device_thermostat 0xe1ff
#define MATSYM_device_unknown 0xe339
#define MATSYM_devices 0xe1b1
#define MATSYM_devices_fold 0xebde
#define MATSYM_devices_other 0xe337
#define MATSYM_dew_point 0xf879
#define MATSYM_dialer_sip 0xe0bb
#define MATSYM_dialpad 0xe0bc
#define MATSYM_diamond 0xead5
#define MATSYM_difference 0xeb7d
#define MATSYM_dining 0xeff4
#define MATSYM_dinner_dining 0xea57
#define MATSYM_directions 0xe52e
#define MATSYM_directions_bike 0xe52f
#define MATSYM_directions_boat 0xe532
#define MATSYM_directions_boat_filled 0xeff5
#define MATSYM_directions_bus 0xe530
#define MATSYM_directions_bus_filled 0xeff6
#define MATSYM_directions_car 0xe531
#define MATSYM_directions_car_filled 0xeff7
#define MATSYM_directions_ferry 0xe532
#define MATSYM_directions_off 0xf10f
#define MATSYM_directions_railway 0xe534
#define MATSYM_directions_railway_filled 0xeff8
#define MATSYM_directions_run 0xe566
#define MATSYM_directions_subway 0xe533
#define MATSYM_directions_subway_filled 0xeff9
#define MATSYM_directions_train 0xe534
#define MATSYM_directions_transit 0xe535
#define MATSYM_directions_transit_filled 0xeffa
#define MATSYM_directions_walk 0xe536
#define MATSYM_dirty_lens 0xef4b
#define MATSYM_disabled_by_default 0xf230
#define MATSYM_disabled_visible 0xe76e
#define MATSYM_disc_full 0xe610
#define MATSYM_discord 0xea6c
#define MATSYM_discount 0xebc9
#define MATSYM_display_settings 0xeb97
#define MATSYM_diversity_1 0xf8d7
#define MATSYM_diversity_2 0xf8d8
#define MATSYM_diversity_3 0xf8d9
#define MATSYM_dnd_forwardslash 0xe611
#define MATSYM_dns 0xe875
#define MATSYM_do_disturb 0xf08c
#define MATSYM_do_disturb_alt 0xf08d
#define MATSYM_do_disturb_off 0xf08e
#define MATSYM_do_disturb_on 0xf08f
#define MATSYM_do_not_disturb 0xe612
#define MATSYM_do_not_disturb_alt 0xe611
#define MATSYM_do_not_disturb_off 0xe643
#define MATSYM_do_not_disturb_on 0xe644
#define MATSYM_do_not_disturb_on_total_silence 0xeffb
#define MATSYM_do_not_step 0xf19f
#define MATSYM_do_not_touch 0xf1b0
#define MATSYM_dock 0xe30e
#define MATSYM_document_scanner 0xe5fa
#define MATSYM_domain 0xe7ee
#define MATSYM_domain_add 0xeb62
#define MATSYM_domain_disabled 0xe0ef
#define MATSYM_domain_verification 0xef4c
#define MATSYM_done 0xe876
#define MATSYM_done_all 0xe877
#define MATSYM_done_outline 0xe92f
#define MATSYM_donut_large 0xe917
#define MATSYM_donut_small 0xe918
#define MATSYM_door_back 0xeffc
#define MATSYM_door_front 0xeffd
#define MATSYM_door_sliding 0xeffe
#define MATSYM_doorbell 0xefff
#define MATSYM_double_arrow 0xea50
#define MATSYM_downhill_skiing 0xe509
#define MATSYM_download 0xf090
#define MATSYM_download_done 0xf091
#define MATSYM_download_for_offline 0xf000
#define MATSYM_downloading 0xf001
#define MATSYM_drafts 0xe151
#define MATSYM_drag_handle 0xe25d
#define MATSYM_drag_indicator 0xe945
#define MATSYM_draw 0xe746
#define MATSYM_drive_eta 0xe613
#define MATSYM_drive_file_move 0xe675
#define MATSYM_drive_file_move_outline 0xe9a1
#define MATSYM_drive_file_move_rtl 0xe76d
#define MATSYM_drive_file_rename_outline 0xe9a2
#define MATSYM_drive_folder_upload 0xe9a3
#define MATSYM_dry 0xf1b3
#define MATSYM_dry_cleaning 0xea58
#define MATSYM_duo 0xe9a5
#define MATSYM_dvr 0xe1b2
#define MATSYM_dynamic_feed 0xea14
#define MATSYM_dynamic_form 0xf1bf
#define MATSYM_e_mobiledata 0xf002
#define MATSYM_earbuds 0xf003
#define MATSYM_earbuds_battery 0xf004
#define MATSYM_east 0xf1df
#define MATSYM_eco 0xea35
#define MATSYM_edgesensor_high 0xf005
#define MATSYM_edgesensor_low 0xf006
#define MATSYM_edit 0xe3c9
#define MATSYM_edit_attributes 0xe578
#define MATSYM_edit_calendar 0xe742
#define MATSYM_edit_document 0xf88c
#define MATSYM_edit_location 0xe568
#define MATSYM_edit_location_alt 0xe1c5
#define MATSYM_edit_note 0xe745
#define MATSYM_edit_notifications 0xe525
#define MATSYM_edit_off 0xe950
#define MATSYM_edit_road 0xef4d
#define MATSYM_edit_square 0xf88d
#define MATSYM_egg 0xeacc
#define MATSYM_egg_alt 0xeac8
#define MATSYM_eject 0xe8fb
#define MATSYM_elderly 0xf21a
#define MATSYM_elderly_woman 0xeb69
#define MATSYM_electric_bike 0xeb1b
#define MATSYM_electric_bolt 0xec1c
#define MATSYM_electric_car 0xeb1c
#define MATSYM_electric_meter 0xec1b
#define MATSYM_electric_moped 0xeb1d
#define MATSYM_electric_rickshaw 0xeb1e
#define MATSYM_electric_scooter 0xeb1f
#define MATSYM_electrical_services 0xf102
#define MATSYM_elevator 0xf1a0
#define MATSYM_email 0xe0be
#define MATSYM_emergency 0xe1eb
#define MATSYM_emergency_recording 0xebf4
#define MATSYM_emergency_share 0xebf6
#define MATSYM_emoji_emotions 0xea22
#define MATSYM_emoji_events 0xea23
#define MATSYM_emoji_flags 0xea1a
#define MATSYM_emoji_food_beverage 0xea1b
#define MATSYM_emoji_nature 0xea1c
#define MATSYM_emoji_objects 0xea24
#define MATSYM_emoji_people 0xea1d
#define MATSYM_emoji_symbols 0xea1e
#define MATSYM_emoji_transportation 0xea1f
#define MATSYM_energy_savings_leaf 0xec1a
#define MATSYM_engineering 0xea3d
#define MATSYM_enhance_photo_translate 0xe8fc
#define MATSYM_enhanced_encryption 0xe63f
#define MATSYM_equalizer 0xe01d
#define MATSYM_error 0xe000
#define MATSYM_error_outline 0xe001
#define MATSYM_escalator 0xf1a1
#define MATSYM_escalator_warning 0xf1ac
#define MATSYM_euro 0xea15
#define MATSYM_euro_symbol 0xe926
#define MATSYM_ev_station 0xe56d
#define MATSYM_event 0xe878
#define MATSYM_event_available 0xe614
#define MATSYM_event_busy 0xe615
#define MATSYM_event_note 0xe616
#define MATSYM_event_repeat 0xeb7b
#define MATSYM_event_seat 0xe903
#define MATSYM_exit_to_app 0xe879
#define MATSYM_expand 0xe94f
#define MATSYM_expand_circle_down 0xe7cd
#define MATSYM_expand_less 0xe5ce
#define MATSYM_expand_more 0xe5cf
#define MATSYM_explicit 0xe01e
#define MATSYM_explore 0xe87a
#define MATSYM_explore_off 0xe9a8
#define MATSYM_exposure 0xe3ca
#define MATSYM_exposure_minus_1 0xe3cb
#define MATSYM_exposure_minus_2 0xe3cc
#define MATSYM_exposure_neg_1 0xe3cb
#define MATSYM_exposure_neg_2 0xe3cc
#define MATSYM_exposure_plus_1 0xe3cd
#define MATSYM_exposure_plus_2 0xe3ce
#define MATSYM_exposure_zero 0xe3cf
#define MATSYM_extension 0xe87b
#define MATSYM_extension_off 0xe4f5
#define MATSYM_face 0xe87c
#define MATSYM_face_2 0xf8da
#define MATSYM_face_3 0xf8db
#define MATSYM_face_4 0xf8dc
#define MATSYM_face_5 0xf8dd
#define MATSYM_face_6 0xf8de
#define MATSYM_face_retouching_natural 0xef4e
#define MATSYM_face_retouching_off 0xf007
#define MATSYM_facebook 0xf234
#define MATSYM_fact_check 0xf0c5
#define MATSYM_factory 0xebbc
#define MATSYM_family_restroom 0xf1a2
#define MATSYM_fast_forward 0xe01f
#define MATSYM_fast_rewind 0xe020
#define MATSYM_fastfood 0xe57a
#define MATSYM_favorite 0xe87d
#define MATSYM_favorite_border 0xe87e
#define MATSYM_favorite_outline 0xe87e
#define MATSYM_fax 0xead8
#define MATSYM_featured_play_list 0xe06d
#define MATSYM_featured_video 0xe06e
#define MATSYM_feed 0xf009
#define MATSYM_feedback 0xe87f
#define MATSYM_female 0xe590
#define MATSYM_fence 0xf1f6
#define MATSYM_festival 0xea68
#define MATSYM_fiber_dvr 0xe05d
#define MATSYM_fiber_manual_record 0xe061
#define MATSYM_fiber_new 0xe05e
#define MATSYM_fiber_pin 0xe06a
#define MATSYM_fiber_smart_record 0xe062
#define MATSYM_file_copy 0xe173
#define MATSYM_file_download 0xe2c4
#define MATSYM_file_download_done 0xe9aa
#define MATSYM_file_download_off 0xe4fe
#define MATSYM_file_open 0xeaf3
#define MATSYM_file_present 0xea0e
#define MATSYM_file_upload 0xe2c6
#define MATSYM_file_upload_off 0xf886
#define MATSYM_filter 0xe3d3
#define MATSYM_filter_1 0xe3d0
#define MATSYM_filter_2 0xe3d1
#define MATSYM_filter_3 0xe3d2
#define MATSYM_filter_4 0xe3d4
#define MATSYM_filter_5 0xe3d5
#define MATSYM_filter_6 0xe3d6
#define MATSYM_filter_7 0xe3d7
#define MATSYM_filter_8 0xe3d8
#define MATSYM_filter_9 0xe3d9
#define MATSYM_filter_9_plus 0xe3da
#define MATSYM_filter_alt 0xef4f
#define MATSYM_filter_alt_off 0xeb32
#define MATSYM_filter_b_and_w 0xe3db
#define MATSYM_filter_center_focus 0xe3dc
#define MATSYM_filter_drama 0xe3dd
#define MATSYM_filter_frames 0xe3de
#define MATSYM_filter_hdr 0xe3df
#define MATSYM_filter_list 0xe152
#define MATSYM_filter_list_alt 0xe94e
#define MATSYM_filter_list_off 0xeb57
#define MATSYM_filter_none 0xe3e0
#define MATSYM_filter_tilt_shift 0xe3e2
#define MATSYM_filter_vintage 0xe3e3
#define MATSYM_find_in_page 0xe880
#define MATSYM_find_replace 0xe881
#define MATSYM_fingerprint 0xe90d
#define MATSYM_fire_extinguisher 0xf1d8
#define MATSYM_fire_hydrant 0xf1a3
#define MATSYM_fire_hydrant_alt 0xf8f1
#define MATSYM_fire_truck 0xf8f2
#define MATSYM_fireplace 0xea43
#define MATSYM_first_page 0xe5dc
#define MATSYM_fit_screen 0xea10
#define MATSYM_fitbit 0xe82b
#define MATSYM_fitness_center 0xeb43
#define MATSYM_flag 0xe153
#define MATSYM_flag_circle 0xeaf8
#define MATSYM_flaky 0xef50
#define MATSYM_flare 0xe3e4
#define MATSYM_flash_auto 0xe3e5
#define MATSYM_flash_off 0xe3e6
#define MATSYM_flash_on 0xe3e7
#define MATSYM_flashlight_off 0xf00a
#define MATSYM_flashlight_on 0xf00b
#define MATSYM_flatware 0xf00c
#define MATSYM_flight 0xe539
#define MATSYM_flight_class 0xe7cb
#define MATSYM_flight_land 0xe904
#define MATSYM_flight_takeoff 0xe905
#define MATSYM_flip 0xe3e8
#define MATSYM_flip_camera_android 0xea37
#define MATSYM_flip_camera_ios 0xea38
#define MATSYM_flip_to_back 0xe882
#define MATSYM_flip_to_front 0xe883
#define MATSYM_flood 0xebe6
#define MATSYM_flourescent 0xec31
#define MATSYM_flutter_dash 0xe00b
#define MATSYM_fmd_bad 0xf00e
#define MATSYM_fmd_good 0xf00f
#define MATSYM_foggy 0xe818
#define MATSYM_folder 0xe2c7
#define MATSYM_folder_copy 0xebbd
#define MATSYM_folder_delete 0xeb34
#define MATSYM_folder_off 0xeb83
#define MATSYM_folder_open 0xe2c8
#define MATSYM_folder_shared 0xe2c9
#define MATSYM_folder_special 0xe617
#define MATSYM_folder_zip 0xeb2c
#define MATSYM_follow_the_signs 0xf222
#define MATSYM_font_download 0xe167
#define MATSYM_font_download_off 0xe4f9
#define MATSYM_food_bank 0xf1f2
#define MATSYM_forest 0xea99
#define MATSYM_fork_left 0xeba0
#define MATSYM_fork_right 0xebac
#define MATSYM_forklift 0xf868
#define MATSYM_format_align_center 0xe234
#define MATSYM_format_align_justify 0xe235
#define MATSYM_format_align_left 0xe236
#define MATSYM_format_align_right 0xe237
#define MATSYM_format_bold 0xe238
#define MATSYM_format_clear 0xe239
#define MATSYM_format_color_fill 0xe23a
#define MATSYM_format_color_reset 0xe23b
#define MATSYM_format_color_text 0xe23c
#define MATSYM_format_indent_decrease 0xe23d
#define MATSYM_format_indent_increase 0xe23e
#define MATSYM_format_italic 0xe23f
#define MATSYM_format_line_spacing 0xe240
#define MATSYM_format_list_bulleted 0xe241
#define MATSYM_format_list_bulleted_add 0xf849
#define MATSYM_format_list_numbered 0xe242
#define MATSYM_format_list_numbered_rtl 0xe267
#define MATSYM_format_overline 0xeb65
#define MATSYM_format_paint 0xe243
#define MATSYM_format_quote 0xe244
#define MATSYM_format_shapes 0xe25e
#define MATSYM_format_size 0xe245
#define MATSYM_format_strikethrough 0xe246
#define MATSYM_format_textdirection_l_to_r 0xe247
#define MATSYM_format_textdirection_r_to_l 0xe248
#define MATSYM_format_underline 0xe249
#define MATSYM_format_underlined 0xe249
#define MATSYM_fort 0xeaad
#define MATSYM_forum 0xe0bf
#define MATSYM_forward 0xe154
#define MATSYM_forward_10 0xe056
#define MATSYM_forward_30 0xe057
#define MATSYM_forward_5 0xe058
#define MATSYM_forward_to_inbox 0xf187
#define MATSYM_foundation 0xf200
#define MATSYM_free_breakfast 0xeb44
#define MATSYM_free_cancellation 0xe748
#define MATSYM_front_hand 0xe769
#define MATSYM_front_loader 0xf869
#define MATSYM_fullscreen 0xe5d0
#define MATSYM_fullscreen_exit 0xe5d1
#define MATSYM_functions 0xe24a
#define MATSYM_g_mobiledata 0xf010
#define MATSYM_g_translate 0xe927
#define MATSYM_gamepad 0xe30f
#define MATSYM_games 0xe021
#define MATSYM_garage 0xf011
#define MATSYM_gas_meter 0xec19
#define MATSYM_gavel 0xe90e
#define MATSYM_generating_tokens 0xe749
#define MATSYM_gesture 0xe155
#define MATSYM_get_app 0xe884
#define MATSYM_gif 0xe908
#define MATSYM_gif_box 0xe7a3
#define MATSYM_girl 0xeb68
#define MATSYM_gite 0xe58b
#define MATSYM_goat 0x10fffd
#define MATSYM_golf_course 0xeb45
#define MATSYM_gpp_bad 0xf012
#define MATSYM_gpp_good 0xf013
#define MATSYM_gpp_maybe 0xf014
#define MATSYM_gps_fixed 0xe1b3
#define MATSYM_gps_not_fixed 0xe1b4
#define MATSYM_gps_off 0xe1b5
#define MATSYM_grade 0xe885
#define MATSYM_gradient 0xe3e9
#define MATSYM_grading 0xea4f
#define MATSYM_grain 0xe3ea
#define MATSYM_graphic_eq 0xe1b8
#define MATSYM_grass 0xf205
#define MATSYM_grid_3x3 0xf015
#define MATSYM_grid_4x4 0xf016
#define MATSYM_grid_goldenratio 0xf017
#define MATSYM_grid_off 0xe3eb
#define MATSYM_grid_on 0xe3ec
#define MATSYM_grid_view 0xe9b0
#define MATSYM_group 0xe7ef
#define MATSYM_group_add 0xe7f0
#define MATSYM_group_off 0xe747
#define MATSYM_group_remove 0xe7ad
#define MATSYM_group_work 0xe886
#define MATSYM_groups 0xf233
#define MATSYM_groups_2 0xf8df
#define MATSYM_groups_3 0xf8e0
#define MATSYM_h_mobiledata 0xf018
#define MATSYM_h_plus_mobiledata 0xf019
#define MATSYM_hail 0xe9b1
#define MATSYM_handshake 0xebcb
#define MATSYM_handyman 0xf10b
#define MATSYM_hardware 0xea59
#define MATSYM_hd 0xe052
#define MATSYM_hdr_auto 0xf01a
#define MATSYM_hdr_auto_select 0xf01b
#define MATSYM_hdr_enhanced_select 0xef51
#define MATSYM_hdr_off 0xe3ed
#define MATSYM_hdr_off_select 0xf01c
#define MATSYM_hdr_on 0xe3ee
#define MATSYM_hdr_on_select 0xf01d
#define MATSYM_hdr_plus 0xf01e
#define MATSYM_hdr_strong 0xe3f1
#define MATSYM_hdr_weak 0xe3f2
#define MATSYM_headphones 0xf01f
#define MATSYM_headphones_battery 0xf020
#define MATSYM_headset 0xe310
#define MATSYM_headset_mic 0xe311
#define MATSYM_headset_off 0xe33a
#define MATSYM_healing 0xe3f3
#define MATSYM_health_and_safety 0xe1d5
#define MATSYM_hearing 0xe023
#define MATSYM_hearing_disabled 0xf104
#define MATSYM_heart_broken 0xeac2
#define MATSYM_heat_pump 0xec18
#define MATSYM_height 0xea16
#define MATSYM_help 0xe887
#define MATSYM_help_center 0xf1c0
#define MATSYM_help_outline 0xe8fd
#define MATSYM_hevc 0xf021
#define MATSYM_hexagon 0xeb39
#define MATSYM_hide_image 0xf022
#define MATSYM_hide_source 0xf023
#define MATSYM_high_quality 0xe024
#define MATSYM_highlight 0xe25f
#define MATSYM_highlight_alt 0xef52
#define MATSYM_highlight_off 0xe888
#define MATSYM_highlight_remove 0xe888
#define MATSYM_hiking 0xe50a
#define MATSYM_history 0xe889
#define MATSYM_history_edu 0xea3e
#define MATSYM_history_toggle_off 0xf17d
#define MATSYM_hive 0xeaa6
#define MATSYM_hls 0xeb8a
#define MATSYM_hls_off 0xeb8c
#define MATSYM_holiday_village 0xe58a
#define MATSYM_home 0xe88a
#define MATSYM_home_filled 0xe9b2
#define MATSYM_home_max 0xf024
#define MATSYM_home_mini 0xf025
#define MATSYM_home_repair_service 0xf100
#define MATSYM_home_work 0xea09
#define MATSYM_horizontal_distribute 0xe014
#define MATSYM_horizontal_rule 0xf108
#define MATSYM_horizontal_split 0xe947
#define MATSYM_hot_tub 0xeb46
#define MATSYM_hotel 0xe53a
#define MATSYM_hotel_class 0xe743
#define MATSYM_hourglass_bottom 0xea5c
#define MATSYM_hourglass_disabled 0xef53
#define MATSYM_hourglass_empty 0xe88b
#define MATSYM_hourglass_full 0xe88c
#define MATSYM_hourglass_top 0xea5b
#define MATSYM_house 0xea44
#define MATSYM_house_siding 0xf202
#define MATSYM_houseboat 0xe584
#define MATSYM_how_to_reg 0xe174
#define MATSYM_how_to_vote 0xe175
#define MATSYM_html 0xeb7e
#define MATSYM_http 0xe902
#define MATSYM_https 0xe88d
#define MATSYM_hub 0xe9f4
#define MATSYM_hvac 0xf10e
#define MATSYM_ice_skating 0xe50b
#define MATSYM_icecream 0xea69
#define MATSYM_image 0xe3f4
#define MATSYM_image_aspect_ratio 0xe3f5
#define MATSYM_image_not_supported 0xf116
#define MATSYM_image_search 0xe43f
#define MATSYM_imagesearch_roller 0xe9b4
#define MATSYM_import_contacts 0xe0e0
#define MATSYM_import_export 0xe0c3
#define MATSYM_important_devices 0xe912
#define MATSYM_inbox 0xe156
#define MATSYM_incomplete_circle 0xe79b
#define MATSYM_indeterminate_check_box 0xe909
#define MATSYM_info 0xe88e
#define MATSYM_info_outline 0xe88f
#define MATSYM_input 0xe890
#define MATSYM_insert_chart 0xe24b
#define MATSYM_insert_chart_outlined 0xe26a
#define MATSYM_insert_comment 0xe24c
#define MATSYM_insert_drive_file 0xe24d
#define MATSYM_insert_emoticon 0xe24e
#define MATSYM_insert_invitation 0xe24f
#define MATSYM_insert_link 0xe250
#define MATSYM_insert_page_break 0xeaca
#define MATSYM_insert_photo 0xe251
#define MATSYM_insights 0xf092
#define MATSYM_install_desktop 0xeb71
#define MATSYM_install_mobile 0xeb72
#define MATSYM_integration_instructions 0xef54
#define MATSYM_interests 0xe7c8
#define MATSYM_interpreter_mode 0xe83b
#define MATSYM_inventory 0xe179
#define MATSYM_inventory_2 0xe1a1
#define MATSYM_invert_colors 0xe891
#define MATSYM_invert_colors_off 0xe0c4
#define MATSYM_invert_colors_on 0xe891
#define MATSYM_ios_share 0xe6b8
#define MATSYM_iron 0xe583
#define MATSYM_iso 0xe3f6
#define MATSYM_javascript 0xeb7c
#define MATSYM_join_full 0xeaeb
#define MATSYM_join_inner 0xeaf4
#define MATSYM_join_left 0xeaf2
#define MATSYM_join_right 0xeaea
#define MATSYM_kayaking 0xe50c
#define MATSYM_kebab_dining 0xe842
#define MATSYM_key 0xe73c
#define MATSYM_key_off 0xeb84
#define MATSYM_keyboard 0xe312
#define MATSYM_keyboard_alt 0xf028
#define MATSYM_keyboard_arrow_down 0xe313
#define MATSYM_keyboard_arrow_left 0xe314
#define MATSYM_keyboard_arrow_right 0xe315
#define MATSYM_keyboard_arrow_up 0xe316
#define MATSYM_keyboard_backspace 0xe317
#define MATSYM_keyboard_capslock 0xe318
#define MATSYM_keyboard_command 0xeae0
#define MATSYM_keyboard_command_key 0xeae7
#define MATSYM_keyboard_control 0xe5d3
#define MATSYM_keyboard_control_key 0xeae6
#define MATSYM_keyboard_double_arrow_down 0xead0
#define MATSYM_keyboard_double_arrow_left 0xeac3
#define MATSYM_keyboard_double_arrow_right 0xeac9
#define MATSYM_keyboard_double_arrow_up 0xeacf
#define MATSYM_keyboard_hide 0xe31a
#define MATSYM_keyboard_option 0xeadf
#define MATSYM_keyboard_option_key 0xeae8
#define MATSYM_keyboard_return 0xe31b
#define MATSYM_keyboard_tab 0xe31c
#define MATSYM_keyboard_voice 0xe31d
#define MATSYM_king_bed 0xea45
#define MATSYM_kitchen 0xeb47
#define MATSYM_kitesurfing 0xe50d
#define MATSYM_label 0xe892
#define MATSYM_label_important 0xe937
#define MATSYM_label_important_outline 0xe948
#define MATSYM_label_off 0xe9b6
#define MATSYM_label_outline 0xe893
#define MATSYM_lan 0xeb2f
#define MATSYM_landscape 0xe3f7
#define MATSYM_landslide 0xebd7
#define MATSYM_language 0xe894
#define MATSYM_laptop 0xe31e
#define MATSYM_laptop_chromebook 0xe31f
#define MATSYM_laptop_mac 0xe320
#define MATSYM_laptop_windows 0xe321
#define MATSYM_last_page 0xe5dd
#define MATSYM_launch 0xe895
#define MATSYM_layers 0xe53b
#define MATSYM_layers_clear 0xe53c
#define MATSYM_leaderboard 0xf20c
#define MATSYM_leak_add 0xe3f8
#define MATSYM_leak_remove 0xe3f9
#define MATSYM_leave_bags_at_home 0xf21b
#define MATSYM_legend_toggle 0xf11b
#define MATSYM_lens 0xe3fa
#define MATSYM_lens_blur 0xf029
#define MATSYM_library_add 0xe02e
#define MATSYM_library_add_check 0xe9b7
#define MATSYM_library_books 0xe02f
#define MATSYM_library_music 0xe030
#define MATSYM_light 0xf02a
#define MATSYM_light_mode 0xe518
#define MATSYM_lightbulb 0xe0f0
#define MATSYM_lightbulb_circle 0xebfe
#define MATSYM_lightbulb_outline 0xe90f
#define MATSYM_line_axis 0xea9a
#define MATSYM_line_style 0xe919
#define MATSYM_line_weight 0xe91a
#define MATSYM_linear_scale 0xe260
#define MATSYM_link 0xe157
#define MATSYM_link_off 0xe16f
#define MATSYM_linked_camera 0xe438
#define MATSYM_liquor 0xea60
#define MATSYM_list 0xe896
#define MATSYM_list_alt 0xe0ee
#define MATSYM_live_help 0xe0c6
#define MATSYM_live_tv 0xe639
#define MATSYM_living 0xf02b
#define MATSYM_local_activity 0xe53f
#define MATSYM_local_airport 0xe53d
#define MATSYM_local_atm 0xe53e
#define MATSYM_local_attraction 0xe53f
#define MATSYM_local_bar 0xe540
#define MATSYM_local_cafe 0xe541
#define MATSYM_local_car_wash 0xe542
#define MATSYM_local_convenience_store 0xe543
#define MATSYM_local_dining 0xe556
#define MATSYM_local_drink 0xe544
#define MATSYM_local_fire_department 0xef55
#define MATSYM_local_florist 0xe545
#define MATSYM_local_gas_station 0xe546
#define MATSYM_local_grocery_store 0xe547
#define MATSYM_local_hospital 0xe548
#define MATSYM_local_hotel 0xe549
#define MATSYM_local_laundry_service 0xe54a
#define MATSYM_local_library 0xe54b
#define MATSYM_local_mall 0xe54c
#define MATSYM_local_movies 0xe54d
#define MATSYM_local_offer 0xe54e
#define MATSYM_local_parking 0xe54f
#define MATSYM_local_pharmacy 0xe550
#define MATSYM_local_phone 0xe551
#define MATSYM_local_pizza 0xe552
#define MATSYM_local_play 0xe553
#define MATSYM_local_police 0xef56
#define MATSYM_local_post_office 0xe554
#define MATSYM_local_print_shop 0xe555
#define MATSYM_local_printshop 0xe555
#define MATSYM_local_restaurant 0xe556
#define MATSYM_local_see 0xe557
#define MATSYM_local_shipping 0xe558
#define MATSYM_local_taxi 0xe559
#define MATSYM_location_city 0xe7f1
#define MATSYM_location_disabled 0xe1b6
#define MATSYM_location_history 0xe55a
#define MATSYM_location_off 0xe0c7
#define MATSYM_location_on 0xe0c8
#define MATSYM_location_pin 0xf1db
#define MATSYM_location_searching 0xe1b7
#define MATSYM_lock 0xe897
#define MATSYM_lock_clock 0xef57
#define MATSYM_lock_open 0xe898
#define MATSYM_lock_outline 0xe899
#define MATSYM_lock_person 0xf8f3
#define MATSYM_lock_reset 0xeade
#define MATSYM_login 0xea77
#define MATSYM_logo_dev 0xead6
#define MATSYM_logout 0xe9ba
#define MATSYM_looks 0xe3fc
#define MATSYM_looks_3 0xe3fb
#define MATSYM_looks_4 0xe3fd
#define MATSYM_looks_5 0xe3fe
#define MATSYM_looks_6 0xe3ff
#define MATSYM_looks_one 0xe400
#define MATSYM_looks_two 0xe401
#define MATSYM_loop 0xe028
#define MATSYM_loupe 0xe402
#define MATSYM_low_priority 0xe16d
#define MATSYM_loyalty 0xe89a
#define MATSYM_lte_mobiledata 0xf02c
#define MATSYM_lte_plus_mobiledata 0xf02d
#define MATSYM_luggage 0xf235
#define MATSYM_lunch_dining 0xea61
#define MATSYM_lyrics 0xec0b
#define MATSYM_macro_off 0xf8d2
#define MATSYM_mail 0xe158
#define MATSYM_mail_lock 0xec0a
#define MATSYM_mail_outline 0xe0e1
#define MATSYM_male 0xe58e
#define MATSYM_man 0xe4eb
#define MATSYM_man_2 0xf8e1
#define MATSYM_man_3 0xf8e2
#define MATSYM_man_4 0xf8e3
#define MATSYM_manage_accounts 0xf02e
#define MATSYM_manage_history 0xebe7
#define MATSYM_manage_search 0xf02f
#define MATSYM_map 0xe55b
#define MATSYM_maps_home_work 0xf030
#define MATSYM_maps_ugc 0xef58
#define MATSYM_margin 0xe9bb
#define MATSYM_mark_as_unread 0xe9bc
#define MATSYM_mark_chat_read 0xf18b
#define MATSYM_mark_chat_unread 0xf189
#define MATSYM_mark_email_read 0xf18c
#define MATSYM_mark_email_unread 0xf18a
#define MATSYM_mark_unread_chat_alt 0xeb9d
#define MATSYM_markunread 0xe159
#define MATSYM_markunread_mailbox 0xe89b
#define MATSYM_masks 0xf218
#define MATSYM_maximize 0xe930
#define MATSYM_media_bluetooth_off 0xf031
#define MATSYM_media_bluetooth_on 0xf032
#define MATSYM_mediation 0xefa7
#define MATSYM_medical_information 0xebed
#define MATSYM_medical_services 0xf109
#define MATSYM_medication 0xf033
#define MATSYM_medication_liquid 0xea87
#define MATSYM_meeting_room 0xeb4f
#define MATSYM_memory 0xe322
#define MATSYM_menu 0xe5d2
#define MATSYM_menu_book 0xea19
#define MATSYM_menu_open 0xe9bd
#define MATSYM_merge 0xeb98
#define MATSYM_merge_type 0xe252
#define MATSYM_message 0xe0c9
#define MATSYM_messenger 0xe0ca
#define MATSYM_messenger_outline 0xe0cb
#define MATSYM_mic 0xe029
#define MATSYM_mic_external_off 0xef59
#define MATSYM_mic_external_on 0xef5a
#define MATSYM_mic_none 0xe02a
#define MATSYM_mic_off 0xe02b
#define MATSYM_microwave 0xf204
#define MATSYM_military_tech 0xea3f
#define MATSYM_minimize 0xe931
#define MATSYM_minor_crash 0xebf1
#define MATSYM_miscellaneous_services 0xf10c
#define MATSYM_missed_video_call 0xe073
#define MATSYM_mms 0xe618
#define MATSYM_mobile_friendly 0xe200
#define MATSYM_mobile_off 0xe201
#define MATSYM_mobile_screen_share 0xe0e7
#define MATSYM_mobiledata_off 0xf034
#define MATSYM_mode 0xf097
#define MATSYM_mode_comment 0xe253
#define MATSYM_mode_edit 0xe254
#define MATSYM_mode_edit_outline 0xf035
#define MATSYM_mode_fan_off 0xec17
#define MATSYM_mode_night 0xf036
#define MATSYM_mode_of_travel 0xe7ce
#define MATSYM_mode_standby 0xf037
#define MATSYM_model_training 0xf0cf
#define MATSYM_monetization_on 0xe263
#define MATSYM_money 0xe57d
#define MATSYM_money_off 0xe25c
#define MATSYM_money_off_csred 0xf038
#define MATSYM_monitor 0xef5b
#define MATSYM_monitor_heart 0xeaa2
#define MATSYM_monitor_weight 0xf039
#define MATSYM_monochrome_photos 0xe403
#define MATSYM_mood 0xe7f2
#define MATSYM_mood_bad 0xe7f3
#define MATSYM_moped 0xeb28
#define MATSYM_more 0xe619
#define MATSYM_more_horiz 0xe5d3
#define MATSYM_more_time 0xea5d
#define MATSYM_more_vert 0xe5d4
#define MATSYM_mosque 0xeab2
#define MATSYM_motion_photos_auto 0xf03a
#define MATSYM_motion_photos_off 0xe9c0
#define MATSYM_motion_photos_on 0xe9c1
#define MATSYM_motion_photos_pause 0xf227
#define MATSYM_motion_photos_paused 0xe9c2
#define MATSYM_motorcycle 0xe91b
#define MATSYM_mouse 0xe323
#define MATSYM_move_down 0xeb61
#define MATSYM_move_to_inbox 0xe168
#define MATSYM_move_up 0xeb64
#define MATSYM_movie 0xe02c
#define MATSYM_movie_creation 0xe404
#define MATSYM_movie_edit 0xf840
#define MATSYM_movie_filter 0xe43a
#define MATSYM_moving 0xe501
#define MATSYM_mp 0xe9c3
#define MATSYM_multiline_chart 0xe6df
#define MATSYM_multiple_stop 0xf1b9
#define MATSYM_multitrack_audio 0xe1b8
#define MATSYM_museum 0xea36
#define MATSYM_music_note 0xe405
#define MATSYM_music_off 0xe440
#define MATSYM_music_video 0xe063
#define MATSYM_my_library_add 0xe02e
#define MATSYM_my_library_books 0xe02f
#define MATSYM_my_library_music 0xe030
#define MATSYM_my_location 0xe55c
#define MATSYM_nat 0xef5c
#define MATSYM_nature 0xe406
#define MATSYM_nature_people 0xe407
#define MATSYM_navigate_before 0xe408
#define MATSYM_navigate_next 0xe409
#define MATSYM_navigation 0xe55d
#define MATSYM_near_me 0xe569
#define MATSYM_near_me_disabled 0xf1ef
#define MATSYM_nearby_error 0xf03b
#define MATSYM_nearby_off 0xf03c
#define MATSYM_nest_cam_wired_stand 0xec16
#define MATSYM_network_cell 0xe1b9
#define MATSYM_network_check 0xe640
#define MATSYM_network_locked 0xe61a
#define MATSYM_network_ping 0xebca
#define MATSYM_network_wifi 0xe1ba
#define MATSYM_network_wifi_1_bar 0xebe4
#define MATSYM_network_wifi_2_bar 0xebd6
#define MATSYM_network_wifi_3_bar 0xebe1
#define MATSYM_new_label 0xe609
#define MATSYM_new_releases 0xe031
#define MATSYM_newspaper 0xeb81
#define MATSYM_next_plan 0xef5d
#define MATSYM_next_week 0xe16a
#define MATSYM_nfc 0xe1bb
#define MATSYM_night_shelter 0xf1f1
#define MATSYM_nightlife 0xea62
#define MATSYM_nightlight 0xf03d
#define MATSYM_nightlight_round 0xef5e
#define MATSYM_nights_stay 0xea46
#define MATSYM_no_accounts 0xf03e
#define MATSYM_no_adult_content 0xf8fe
#define MATSYM_no_backpack 0xf237
#define MATSYM_no_cell 0xf1a4
#define MATSYM_no_crash 0xebf0
#define MATSYM_no_drinks 0xf1a5
#define MATSYM_no_encryption 0xe641
#define MATSYM_no_encryption_gmailerrorred 0xf03f
#define MATSYM_no_flash 0xf1a6
#define MATSYM_no_food 0xf1a7
#define MATSYM_no_luggage 0xf23b
#define MATSYM_no_meals 0xf1d6
#define MATSYM_no_meals_ouline 0xf229
#define MATSYM_no_meeting_room 0xeb4e
#define MATSYM_no_photography 0xf1a8
#define MATSYM_no_sim 0xe0cc
#define MATSYM_no_stroller 0xf1af
#define MATSYM_no_transfer 0xf1d5
#define MATSYM_noise_aware 0xebec
#define MATSYM_noise_control_off 0xebf3
#define MATSYM_nordic_walking 0xe50e
#define MATSYM_north 0xf1e0
#define MATSYM_north_east 0xf1e1
#define MATSYM_north_west 0xf1e2
#define MATSYM_not_accessible 0xf0fe
#define MATSYM_not_interested 0xe033
#define MATSYM_not_listed_location 0xe575
#define MATSYM_not_started 0xf0d1
#define MATSYM_note 0xe06f
#define MATSYM_note_add 0xe89c
#define MATSYM_note_alt 0xf040
#define MATSYM_notes 0xe26c
#define MATSYM_notification_add 0xe399
#define MATSYM_notification_important 0xe004
#define MATSYM_notifications 0xe7f4
#define MATSYM_notifications_active 0xe7f7
#define MATSYM_notifications_none 0xe7f5
#define MATSYM_notifications_off 0xe7f6
#define MATSYM_notifications_on 0xe7f7
#define MATSYM_notifications_paused 0xe7f8
#define MATSYM_now_wallpaper 0xe1bc
#define MATSYM_now_widgets 0xe1bd
#define MATSYM_numbers 0xeac7
#define MATSYM_offline_bolt 0xe932
#define MATSYM_offline_pin 0xe90a
#define MATSYM_offline_share 0xe9c5
#define MATSYM_oil_barrel 0xec15
#define MATSYM_on_device_training 0xebfd
#define MATSYM_ondemand_video 0xe63a
#define MATSYM_online_prediction 0xf0eb
#define MATSYM_opacity 0xe91c
#define MATSYM_open_in_browser 0xe89d
#define MATSYM_open_in_full 0xf1ce
#define MATSYM_open_in_new 0xe89e
#define MATSYM_open_in_new_off 0xe4f6
#define MATSYM_open_with 0xe89f
#define MATSYM_other_houses 0xe58c
#define MATSYM_outbond 0xf228
#define MATSYM_outbound 0xe1ca
#define MATSYM_outbox 0xef5f
#define MATSYM_outdoor_grill 0xea47
#define MATSYM_outgoing_mail 0xf0d2
#define MATSYM_outlet 0xf1d4
#define MATSYM_outlined_flag 0xe16e
#define MATSYM_output 0xebbe
#define MATSYM_padding 0xe9c8
#define MATSYM_pages 0xe7f9
#define MATSYM_pageview 0xe8a0
#define MATSYM_paid 0xf041
#define MATSYM_palette 0xe40a
#define MATSYM_pallet 0xf86a
#define MATSYM_pan_tool 0xe925
#define MATSYM_pan_tool_alt 0xebb9
#define MATSYM_panorama 0xe40b
#define MATSYM_panorama_fish_eye 0xe40c
#define MATSYM_panorama_fisheye 0xe40c
#define MATSYM_panorama_horizontal 0xe40d
#define MATSYM_panorama_horizontal_select 0xef60
#define MATSYM_panorama_photosphere 0xe9c9
#define MATSYM_panorama_photosphere_select 0xe9ca
#define MATSYM_panorama_vertical 0xe40e
#define MATSYM_panorama_vertical_select 0xef61
#define MATSYM_panorama_wide_angle 0xe40f
#define MATSYM_panorama_wide_angle_select 0xef62
#define MATSYM_paragliding 0xe50f
#define MATSYM_park 0xea63
#define MATSYM_party_mode 0xe7fa
#define MATSYM_password 0xf042
#define MATSYM_pattern 0xf043
#define MATSYM_pause 0xe034
#define MATSYM_pause_circle 0xe1a2
#define MATSYM_pause_circle_filled 0xe035
#define MATSYM_pause_circle_outline 0xe036
#define MATSYM_pause_presentation 0xe0ea
#define MATSYM_payment 0xe8a1
#define MATSYM_payments 0xef63
#define MATSYM_paypal 0xea8d
#define MATSYM_pedal_bike 0xeb29
#define MATSYM_pending 0xef64
#define MATSYM_pending_actions 0xf1bb
#define MATSYM_pentagon 0xeb50
#define MATSYM_people 0xe7fb
#define MATSYM_people_alt 0xea21
#define MATSYM_people_outline 0xe7fc
#define MATSYM_percent 0xeb58
#define MATSYM_perm_camera_mic 0xe8a2
#define MATSYM_perm_contact_cal 0xe8a3
#define MATSYM_perm_contact_calendar 0xe8a3
#define MATSYM_perm_data_setting 0xe8a4
#define MATSYM_perm_device_info 0xe8a5
#define MATSYM_perm_device_information 0xe8a5
#define MATSYM_perm_identity 0xe8a6
#define MATSYM_perm_media 0xe8a7
#define MATSYM_perm_phone_msg 0xe8a8
#define MATSYM_perm_scan_wifi 0xe8a9
#define MATSYM_person 0xe7fd
#define MATSYM_person_2 0xf8e4
#define MATSYM_person_3 0xf8e5
#define MATSYM_person_4 0xf8e6
#define MATSYM_person_add 0xe7fe
#define MATSYM_person_add_alt 0xea4d
#define MATSYM_person_add_alt_1 0xef65
#define MATSYM_person_add_disabled 0xe9cb
#define MATSYM_person_off 0xe510
#define MATSYM_person_outline 0xe7ff
#define MATSYM_person_pin 0xe55a
#define MATSYM_person_pin_circle 0xe56a
#define MATSYM_person_remove 0xef66
#define MATSYM_person_remove_alt_1 0xef67
#define MATSYM_person_search 0xf106
#define MATSYM_personal_injury 0xe6da
#define MATSYM_personal_video 0xe63b
#define MATSYM_pest_control 0xf0fa
#define MATSYM_pest_control_rodent 0xf0fd
#define MATSYM_pets 0xe91d
#define MATSYM_phishing 0xead7
#define MATSYM_phone 0xe0cd
#define MATSYM_phone_android 0xe324
#define MATSYM_phone_bluetooth_speaker 0xe61b
#define MATSYM_phone_callback 0xe649
#define MATSYM_phone_disabled 0xe9cc
#define MATSYM_phone_enabled 0xe9cd
#define MATSYM_phone_forwarded 0xe61c
#define MATSYM_phone_in_talk 0xe61d
#define MATSYM_phone_iphone 0xe325
#define MATSYM_phone_locked 0xe61e
#define MATSYM_phone_missed 0xe61f
#define MATSYM_phone_paused 0xe620
#define MATSYM_phonelink 0xe326
#define MATSYM_phonelink_erase 0xe0db
#define MATSYM_phonelink_lock 0xe0dc
#define MATSYM_phonelink_off 0xe327
#define MATSYM_phonelink_ring 0xe0dd
#define MATSYM_phonelink_setup 0xe0de
#define MATSYM_photo 0xe410
#define MATSYM_photo_album 0xe411
#define MATSYM_photo_camera 0xe412
#define MATSYM_photo_camera_back 0xef68
#define MATSYM_photo_camera_front 0xef69
#define MATSYM_photo_filter 0xe43b
#define MATSYM_photo_library 0xe413
#define MATSYM_photo_size_select_actual 0xe432
#define MATSYM_photo_size_select_large 0xe433
#define MATSYM_photo_size_select_small 0xe434
#define MATSYM_php 0xeb8f
#define MATSYM_piano 0xe521
#define MATSYM_piano_off 0xe520
#define MATSYM_picture_as_pdf 0xe415
#define MATSYM_picture_in_picture 0xe8aa
#define MATSYM_picture_in_picture_alt 0xe911
#define MATSYM_pie_chart 0xe6c4
#define MATSYM_pie_chart_outline 0xf044
#define MATSYM_pie_chart_outlined 0xe6c5
#define MATSYM_pin 0xf045
#define MATSYM_pin_drop 0xe55e
#define MATSYM_pin_end 0xe767
#define MATSYM_pin_invoke 0xe763
#define MATSYM_pinch 0xeb38
#define MATSYM_pivot_table_chart 0xe9ce
#define MATSYM_pix 0xeaa3
#define MATSYM_place 0xe55f
#define MATSYM_plagiarism 0xea5a
#define MATSYM_play_arrow 0xe037
#define MATSYM_play_circle 0xe1c4
#define MATSYM_play_circle_fill 0xe038
#define MATSYM_play_circle_filled 0xe038
#define MATSYM_play_circle_outline 0xe039
#define MATSYM_play_disabled 0xef6a
#define MATSYM_play_for_work 0xe906
#define MATSYM_play_lesson 0xf047
#define MATSYM_playlist_add 0xe03b
#define MATSYM_playlist_add_check 0xe065
#define MATSYM_playlist_add_check_circle 0xe7e6
#define MATSYM_playlist_add_circle 0xe7e5
#define MATSYM_playlist_play 0xe05f
#define MATSYM_playlist_remove 0xeb80
#define MATSYM_plumbing 0xf107
#define MATSYM_plus_one 0xe800
#define MATSYM_podcasts 0xf048
#define MATSYM_point_of_sale 0xf17e
#define MATSYM_policy 0xea17
#define MATSYM_poll 0xe801
#define MATSYM_polyline 0xebbb
#define MATSYM_polymer 0xe8ab
#define MATSYM_pool 0xeb48
#define MATSYM_portable_wifi_off 0xe0ce
#define MATSYM_portrait 0xe416
#define MATSYM_post_add 0xea20
#define MATSYM_power 0xe63c
#define MATSYM_power_input 0xe336
#define MATSYM_power_off 0xe646
#define MATSYM_power_settings_new 0xe8ac
#define MATSYM_precision_manufacturing 0xf049
#define MATSYM_pregnant_woman 0xe91e
#define MATSYM_present_to_all 0xe0df
#define MATSYM_preview 0xf1c5
#define MATSYM_price_change 0xf04a
#define MATSYM_price_check 0xf04b
#define MATSYM_print 0xe8ad
#define MATSYM_print_disabled 0xe9cf
#define MATSYM_priority_high 0xe645
#define MATSYM_privacy_tip 0xf0dc
#define MATSYM_private_connectivity 0xe744
#define MATSYM_production_quantity_limits 0xe1d1
#define MATSYM_propane 0xec14
#define MATSYM_propane_tank 0xec13
#define MATSYM_psychology 0xea4a
#define MATSYM_psychology_alt 0xf8ea
#define MATSYM_public 0xe80b
#define MATSYM_public_off 0xf1ca
#define MATSYM_publish 0xe255
#define MATSYM_published_with_changes 0xf232
#define MATSYM_punch_clock 0xeaa8
#define MATSYM_push_pin 0xf10d
#define MATSYM_qr_code 0xef6b
#define MATSYM_qr_code_2 0xe00a
#define MATSYM_qr_code_scanner 0xf206
#define MATSYM_query_builder 0xe8ae
#define MATSYM_query_stats 0xe4fc
#define MATSYM_question_answer 0xe8af
#define MATSYM_question_mark 0xeb8b
#define MATSYM_queue 0xe03c
#define MATSYM_queue_music 0xe03d
#define MATSYM_queue_play_next 0xe066
#define MATSYM_quick_contacts_dialer 0xe0cf
#define MATSYM_quick_contacts_mail 0xe0d0
#define MATSYM_quickreply 0xef6c
#define MATSYM_quiz 0xf04c
#define MATSYM_quora 0xea98
#define MATSYM_r_mobiledata 0xf04d
#define MATSYM_radar 0xf04e
#define MATSYM_radio 0xe03e
#define MATSYM_radio_button_checked 0xe837
#define MATSYM_radio_button_off 0xe836
#define MATSYM_radio_button_on 0xe837
#define MATSYM_radio_button_unchecked 0xe836
#define MATSYM_railway_alert 0xe9d1
#define MATSYM_ramen_dining 0xea64
#define MATSYM_ramp_left 0xeb9c
#define MATSYM_ramp_right 0xeb96
#define MATSYM_rate_review 0xe560
#define MATSYM_raw_off 0xf04f
#define MATSYM_raw_on 0xf050
#define MATSYM_read_more 0xef6d
#define MATSYM_real_estate_agent 0xe73a
#define MATSYM_rebase_edit 0xf846
#define MATSYM_receipt 0xe8b0
#define MATSYM_receipt_long 0xef6e
#define MATSYM_recent_actors 0xe03f
#define MATSYM_recommend 0xe9d2
#define MATSYM_record_voice_over 0xe91f
#define MATSYM_rectangle 0xeb54
#define MATSYM_recycling 0xe760
#define MATSYM_reddit 0xeaa0
#define MATSYM_redeem 0xe8b1
#define MATSYM_redo 0xe15a
#define MATSYM_reduce_capacity 0xf21c
#define MATSYM_refresh 0xe5d5
#define MATSYM_remember_me 0xf051
#define MATSYM_remove 0xe15b
#define MATSYM_remove_circle 0xe15c
#define MATSYM_remove_circle_outline 0xe15d
#define MATSYM_remove_done 0xe9d3
#define MATSYM_remove_from_queue 0xe067
#define MATSYM_remove_moderator 0xe9d4
#define MATSYM_remove_red_eye 0xe417
#define MATSYM_remove_road 0xebfc
#define MATSYM_remove_shopping_cart 0xe928
#define MATSYM_reorder 0xe8fe
#define MATSYM_repartition 0xf8e8
#define MATSYM_repeat 0xe040
#define MATSYM_repeat_on 0xe9d6
#define MATSYM_repeat_one 0xe041
#define MATSYM_repeat_one_on 0xe9d7
#define MATSYM_replay 0xe042
#define MATSYM_replay_10 0xe059
#define MATSYM_replay_30 0xe05a
#define MATSYM_replay_5 0xe05b
#define MATSYM_replay_circle_filled 0xe9d8
#define MATSYM_reply 0xe15e
#define MATSYM_reply_all 0xe15f
#define MATSYM_report 0xe160
#define MATSYM_report_gmailerrorred 0xf052
#define MATSYM_report_off 0xe170
#define MATSYM_report_problem 0xe8b2
#define MATSYM_request_page 0xf22c
#define MATSYM_request_quote 0xf1b6
#define MATSYM_reset_tv 0xe9d9
#define MATSYM_restart_alt 0xf053
#define MATSYM_restaurant 0xe56c
#define MATSYM_restaurant_menu 0xe561
#define MATSYM_restore 0xe8b3
#define MATSYM_restore_from_trash 0xe938
#define MATSYM_restore_page 0xe929
#define MATSYM_reviews 0xf054
#define MATSYM_rice_bowl 0xf1f5
#define MATSYM_ring_volume 0xe0d1
#define MATSYM_rocket 0xeba5
#define MATSYM_rocket_launch 0xeb9b
#define MATSYM_roller_shades 0xec12
#define MATSYM_roller_shades_closed 0xec11
#define MATSYM_roller_skating 0xebcd
#define MATSYM_roofing 0xf201
#define MATSYM_room 0xe8b4
#define MATSYM_room_preferences 0xf1b8
#define MATSYM_room_service 0xeb49
#define MATSYM_rotate_90_degrees_ccw 0xe418
#define MATSYM_rotate_90_degrees_cw 0xeaab
#define MATSYM_rotate_left 0xe419
#define MATSYM_rotate_right 0xe41a
#define MATSYM_roundabout_left 0xeb99
#define MATSYM_roundabout_right 0xeba3
#define MATSYM_rounded_corner 0xe920
#define MATSYM_route 0xeacd
#define MATSYM_router 0xe328
#define MATSYM_rowing 0xe921
#define MATSYM_rss_feed 0xe0e5
#define MATSYM_rsvp 0xf055
#define MATSYM_rtt 0xe9ad
#define MATSYM_rule 0xf1c2
#define MATSYM_rule_folder 0xf1c9
#define MATSYM_run_circle 0xef6f
#define MATSYM_running_with_errors 0xe51d
#define MATSYM_rv_hookup 0xe642
#define MATSYM_safety_check 0xebef
#define MATSYM_safety_divider 0xe1cc
#define MATSYM_sailing 0xe502
#define MATSYM_sanitizer 0xf21d
#define MATSYM_satellite 0xe562
#define MATSYM_satellite_alt 0xeb3a
#define MATSYM_save 0xe161
#define MATSYM_save_alt 0xe171
#define MATSYM_save_as 0xeb60
#define MATSYM_saved_search 0xea11
#define MATSYM_savings 0xe2eb
#define MATSYM_scale 0xeb5f
#define MATSYM_scanner 0xe329
#define MATSYM_scatter_plot 0xe268
#define MATSYM_schedule 0xe8b5
#define MATSYM_schedule_send 0xea0a
#define MATSYM_schema 0xe4fd
#define MATSYM_school 0xe80c
#define MATSYM_science 0xea4b
#define MATSYM_score 0xe269
#define MATSYM_scoreboard 0xebd0
#define MATSYM_screen_lock_landscape 0xe1be
#define MATSYM_screen_lock_portrait 0xe1bf
#define MATSYM_screen_lock_rotation 0xe1c0
#define MATSYM_screen_rotation 0xe1c1
#define MATSYM_screen_rotation_alt 0xebee
#define MATSYM_screen_search_desktop 0xef70
#define MATSYM_screen_share 0xe0e2
#define MATSYM_screenshot 0xf056
#define MATSYM_screenshot_monitor 0xec08
#define MATSYM_scuba_diving 0xebce
#define MATSYM_sd 0xe9dd
#define MATSYM_sd_card 0xe623
#define MATSYM_sd_card_alert 0xf057
#define MATSYM_sd_storage 0xe1c2
#define MATSYM_search 0xe8b6
#define MATSYM_search_off 0xea76
#define MATSYM_security 0xe32a
#define MATSYM_security_update 0xf058
#define MATSYM_security_update_good 0xf059
#define MATSYM_security_update_warning 0xf05a
#define MATSYM_segment 0xe94b
#define MATSYM_select_all 0xe162
#define MATSYM_self_improvement 0xea78
#define MATSYM_sell 0xf05b
#define MATSYM_send 0xe163
#define MATSYM_send_and_archive 0xea0c
#define MATSYM_send_time_extension 0xeadb
#define MATSYM_send_to_mobile 0xf05c
#define MATSYM_sensor_door 0xf1b5
#define MATSYM_sensor_occupied 0xec10
#define MATSYM_sensor_window 0xf1b4
#define MATSYM_sensors 0xe51e
#define MATSYM_sensors_off 0xe51f
#define MATSYM_sentiment_dissatisfied 0xe811
#define MATSYM_sentiment_neutral 0xe812
#define MATSYM_sentiment_satisfied 0xe813
#define MATSYM_sentiment_satisfied_alt 0xe0ed
#define MATSYM_sentiment_very_dissatisfied 0xe814
#define MATSYM_sentiment_very_satisfied 0xe815
#define MATSYM_set_meal 0xf1ea
#define MATSYM_settings 0xe8b8
#define MATSYM_settings_accessibility 0xf05d
#define MATSYM_settings_applications 0xe8b9
#define MATSYM_settings_backup_restore 0xe8ba
#define MATSYM_settings_bluetooth 0xe8bb
#define MATSYM_settings_brightness 0xe8bd
#define MATSYM_settings_cell 0xe8bc
#define MATSYM_settings_display 0xe8bd
#define MATSYM_settings_ethernet 0xe8be
#define MATSYM_settings_input_antenna 0xe8bf
#define MATSYM_settings_input_component 0xe8c0
#define MATSYM_settings_input_composite 0xe8c1
#define MATSYM_settings_input_hdmi 0xe8c2
#define MATSYM_settings_input_svideo 0xe8c3
#define MATSYM_settings_overscan 0xe8c4
#define MATSYM_settings_phone 0xe8c5
#define MATSYM_settings_power 0xe8c6
#define MATSYM_settings_remote 0xe8c7
#define MATSYM_settings_suggest 0xf05e
#define MATSYM_settings_system_daydream 0xe1c3
#define MATSYM_settings_voice 0xe8c8
#define MATSYM_severe_cold 0xebd3
#define MATSYM_shape_line 0xf8d3
#define MATSYM_share 0xe80d
#define MATSYM_share_arrival_time 0xe524
#define MATSYM_share_location 0xf05f
#define MATSYM_shelves 0xf86e
#define MATSYM_shield 0xe9e0
#define MATSYM_shield_moon 0xeaa9
#define MATSYM_shop 0xe8c9
#define MATSYM_shop_2 0xe19e
#define MATSYM_shop_two 0xe8ca
#define MATSYM_shopify 0xea9d
#define MATSYM_shopping_bag 0xf1cc
#define MATSYM_shopping_basket 0xe8cb
#define MATSYM_shopping_cart 0xe8cc
#define MATSYM_shopping_cart_checkout 0xeb88
#define MATSYM_short_text 0xe261
#define MATSYM_shortcut 0xf060
#define MATSYM_show_chart 0xe6e1
#define MATSYM_shower 0xf061
#define MATSYM_shuffle 0xe043
#define MATSYM_shuffle_on 0xe9e1
#define MATSYM_shutter_speed 0xe43d
#define MATSYM_sick 0xf220
#define MATSYM_sign_language 0xebe5
#define MATSYM_signal_cellular_0_bar 0xf0a8
#define MATSYM_signal_cellular_4_bar 0xe1c8
#define MATSYM_signal_cellular_alt 0xe202
#define MATSYM_signal_cellular_alt_1_bar 0xebdf
#define MATSYM_signal_cellular_alt_2_bar 0xebe3
#define MATSYM_signal_cellular_connected_no_internet_0_bar 0xf0ac
#define MATSYM_signal_cellular_connected_no_internet_4_bar 0xe1cd
#define MATSYM_signal_cellular_no_sim 0xe1ce
#define MATSYM_signal_cellular_nodata 0xf062
#define MATSYM_signal_cellular_null 0xe1cf
#define MATSYM_signal_cellular_off 0xe1d0
#define MATSYM_signal_wifi_0_bar 0xf0b0
#define MATSYM_signal_wifi_4_bar 0xe1d8
#define MATSYM_signal_wifi_4_bar_lock 0xe1d9
#define MATSYM_signal_wifi_bad 0xf063
#define MATSYM_signal_wifi_connected_no_internet_4 0xf064
#define MATSYM_signal_wifi_off 0xe1da
#define MATSYM_signal_wifi_statusbar_4_bar 0xf065
#define MATSYM_signal_wifi_statusbar_connected_no_internet_4 0xf066
#define MATSYM_signal_wifi_statusbar_null 0xf067
#define MATSYM_signpost 0xeb91
#define MATSYM_sim_card 0xe32b
#define MATSYM_sim_card_alert 0xe624
#define MATSYM_sim_card_download 0xf068
#define MATSYM_single_bed 0xea48
#define MATSYM_sip 0xf069
#define MATSYM_skateboarding 0xe511
#define MATSYM_skip_next 0xe044
#define MATSYM_skip_previous 0xe045
#define MATSYM_sledding 0xe512
#define MATSYM_slideshow 0xe41b
#define MATSYM_slow_motion_video 0xe068
#define MATSYM_smart_button 0xf1c1
#define MATSYM_smart_display 0xf06a
#define MATSYM_smart_screen 0xf06b
#define MATSYM_smart_toy 0xf06c
#define MATSYM_smartphone 0xe32c
#define MATSYM_smoke_free 0xeb4a
#define MATSYM_smoking_rooms 0xeb4b
#define MATSYM_sms 0xe625
#define MATSYM_sms_failed 0xe626
#define MATSYM_snapchat 0xea6e
#define MATSYM_snippet_folder 0xf1c7
#define MATSYM_snooze 0xe046
#define MATSYM_snowboarding 0xe513
#define MATSYM_snowing 0xe80f
#define MATSYM_snowmobile 0xe503
#define MATSYM_snowshoeing 0xe514
#define MATSYM_soap 0xf1b2
#define MATSYM_social_distance 0xe1cb
#define MATSYM_solar_power 0xec0f
#define MATSYM_sort 0xe164
#define MATSYM_sort_by_alpha 0xe053
#define MATSYM_sos 0xebf7
#define MATSYM_soup_kitchen 0xe7d3
#define MATSYM_source 0xf1c4
#define MATSYM_south 0xf1e3
#define MATSYM_south_america 0xe7e4
#define MATSYM_south_east 0xf1e4
#define MATSYM_south_west 0xf1e5
#define MATSYM_spa 0xeb4c
#define MATSYM_space_bar 0xe256
#define MATSYM_space_dashboard 0xe66b
#define MATSYM_spatial_audio 0xebeb
#define MATSYM_spatial_audio_off 0xebe8
#define MATSYM_spatial_tracking 0xebea
#define MATSYM_speaker 0xe32d
#define MATSYM_speaker_group 0xe32e
#define MATSYM_speaker_notes 0xe8cd
#define MATSYM_speaker_notes_off 0xe92a
#define MATSYM_speaker_phone 0xe0d2
#define MATSYM_speed 0xe9e4
#define MATSYM_spellcheck 0xe8ce
#define MATSYM_splitscreen 0xf06d
#define MATSYM_spoke 0xe9a7
#define MATSYM_sports 0xea30
#define MATSYM_sports_bar 0xf1f3
#define MATSYM_sports_baseball 0xea51
#define MATSYM_sports_basketball 0xea26
#define MATSYM_sports_cricket 0xea27
#define MATSYM_sports_esports 0xea28
#define MATSYM_sports_football 0xea29
#define MATSYM_sports_golf 0xea2a
#define MATSYM_sports_gymnastics 0xebc4
#define MATSYM_sports_handball 0xea33
#define MATSYM_sports_hockey 0xea2b
#define MATSYM_sports_kabaddi 0xea34
#define MATSYM_sports_martial_arts 0xeae9
#define MATSYM_sports_mma 0xea2c
#define MATSYM_sports_motorsports 0xea2d
#define MATSYM_sports_rugby 0xea2e
#define MATSYM_sports_score 0xf06e
#define MATSYM_sports_soccer 0xea2f
#define MATSYM_sports_tennis 0xea32
#define MATSYM_sports_volleyball 0xea31
#define MATSYM_square 0xeb36
#define MATSYM_square_foot 0xea49
#define MATSYM_ssid_chart 0xeb66
#define MATSYM_stacked_bar_chart 0xe9e6
#define MATSYM_stacked_line_chart 0xf22b
#define MATSYM_stadium 0xeb90
#define MATSYM_stairs 0xf1a9
#define MATSYM_star 0xe838
#define MATSYM_star_border 0xe83a
#define MATSYM_star_border_purple500 0xf099
#define MATSYM_star_half 0xe839
#define MATSYM_star_outline 0xf06f
#define MATSYM_star_purple500 0xf09a
#define MATSYM_star_rate 0xf0ec
#define MATSYM_stars 0xe8d0
#define MATSYM_start 0xe089
#define MATSYM_stay_current_landscape 0xe0d3
#define MATSYM_stay_current_portrait 0xe0d4
#define MATSYM_stay_primary_landscape 0xe0d5
#define MATSYM_stay_primary_portrait 0xe0d6
#define MATSYM_sticky_note_2 0xf1fc
#define MATSYM_stop 0xe047
#define MATSYM_stop_circle 0xef71
#define MATSYM_stop_screen_share 0xe0e3
#define MATSYM_storage 0xe1db
#define MATSYM_store 0xe8d1
#define MATSYM_store_mall_directory 0xe563
#define MATSYM_storefront 0xea12
#define MATSYM_storm 0xf070
#define MATSYM_straight 0xeb95
#define MATSYM_straighten 0xe41c
#define MATSYM_stream 0xe9e9
#define MATSYM_streetview 0xe56e
#define MATSYM_strikethrough_s 0xe257
#define MATSYM_stroller 0xf1ae
#define MATSYM_style 0xe41d
#define MATSYM_subdirectory_arrow_left 0xe5d9
#define MATSYM_subdirectory_arrow_right 0xe5da
#define MATSYM_subject 0xe8d2
#define MATSYM_subscript 0xf111
#define MATSYM_subscriptions 0xe064
#define MATSYM_subtitles 0xe048
#define MATSYM_subtitles_off 0xef72
#define MATSYM_subway 0xe56f
#define MATSYM_summarize 0xf071
#define MATSYM_sunny 0xe81a
#define MATSYM_sunny_snowing 0xe819
#define MATSYM_superscript 0xf112
#define MATSYM_supervised_user_circle 0xe939
#define MATSYM_supervisor_account 0xe8d3
#define MATSYM_support 0xef73
#define MATSYM_support_agent 0xf0e2
#define MATSYM_surfing 0xe515
#define MATSYM_surround_sound 0xe049
#define MATSYM_swap_calls 0xe0d7
#define MATSYM_swap_horiz 0xe8d4
#define MATSYM_swap_horizontal_circle 0xe933
#define MATSYM_swap_vert 0xe8d5
#define MATSYM_swap_vert_circle 0xe8d6
#define MATSYM_swap_vertical_circle 0xe8d6
#define MATSYM_swipe 0xe9ec
#define MATSYM_swipe_down 0xeb53
#define MATSYM_swipe_down_alt 0xeb30
#define MATSYM_swipe_left 0xeb59
#define MATSYM_swipe_left_alt 0xeb33
#define MATSYM_swipe_right 0xeb52
#define MATSYM_swipe_right_alt 0xeb56
#define MATSYM_swipe_up 0xeb2e
#define MATSYM_swipe_up_alt 0xeb35
#define MATSYM_swipe_vertical 0xeb51
#define MATSYM_switch_access_shortcut 0xe7e1
#define MATSYM_switch_access_shortcut_add 0xe7e2
#define MATSYM_switch_account 0xe9ed
#define MATSYM_switch_camera 0xe41e
#define MATSYM_switch_left 0xf1d1
#define MATSYM_switch_right 0xf1d2
#define MATSYM_switch_video 0xe41f
#define MATSYM_synagogue 0xeab0
#define MATSYM_sync 0xe627
#define MATSYM_sync_alt 0xea18
#define MATSYM_sync_disabled 0xe628
#define MATSYM_sync_lock 0xeaee
#define MATSYM_sync_problem 0xe629
#define MATSYM_system_security_update 0xf072
#define MATSYM_system_security_update_good 0xf073
#define MATSYM_system_security_update_warning 0xf074
#define MATSYM_system_update 0xe62a
#define MATSYM_system_update_alt 0xe8d7
#define MATSYM_system_update_tv 0xe8d7
#define MATSYM_tab 0xe8d8
#define MATSYM_tab_unselected 0xe8d9
#define MATSYM_table_bar 0xead2
#define MATSYM_table_chart 0xe265
#define MATSYM_table_restaurant 0xeac6
#define MATSYM_table_rows 0xf101
#define MATSYM_table_view 0xf1be
#define MATSYM_tablet 0xe32f
#define MATSYM_tablet_android 0xe330
#define MATSYM_tablet_mac 0xe331
#define MATSYM_tag 0xe9ef
#define MATSYM_tag_faces 0xe420
#define MATSYM_takeout_dining 0xea74
#define MATSYM_tap_and_play 0xe62b
#define MATSYM_tapas 0xf1e9
#define MATSYM_task 0xf075
#define MATSYM_task_alt 0xe2e6
#define MATSYM_taxi_alert 0xef74
#define MATSYM_telegram 0xea6b
#define MATSYM_temple_buddhist 0xeab3
#define MATSYM_temple_hindu 0xeaaf
#define MATSYM_terminal 0xeb8e
#define MATSYM_terrain 0xe564
#define MATSYM_text_decrease 0xeadd
#define MATSYM_text_fields 0xe262
#define MATSYM_text_format 0xe165
#define MATSYM_text_increase 0xeae2
#define MATSYM_text_rotate_up 0xe93a
#define MATSYM_text_rotate_vertical 0xe93b
#define MATSYM_text_rotation_angledown 0xe93c
#define MATSYM_text_rotation_angleup 0xe93d
#define MATSYM_text_rotation_down 0xe93e
#define MATSYM_text_rotation_none 0xe93f
#define MATSYM_text_snippet 0xf1c6
#define MATSYM_textsms 0xe0d8
#define MATSYM_texture 0xe421
#define MATSYM_theater_comedy 0xea66
#define MATSYM_theaters 0xe8da
#define MATSYM_thermostat 0xf076
#define MATSYM_thermostat_auto 0xf077
#define MATSYM_thumb_down 0xe8db
#define MATSYM_thumb_down_alt 0xe816
#define MATSYM_thumb_down_off_alt 0xe9f2
#define MATSYM_thumb_up 0xe8dc
#define MATSYM_thumb_up_alt 0xe817
#define MATSYM_thumb_up_off_alt 0xe9f3
#define MATSYM_thumbs_up_down 0xe8dd
#define MATSYM_thunderstorm 0xebdb
#define MATSYM_tiktok 0xea7e
#define MATSYM_time_to_leave 0xe62c
#define MATSYM_timelapse 0xe422
#define MATSYM_timeline 0xe922
#define MATSYM_timer 0xe425
#define MATSYM_timer_10 0xe423
#define MATSYM_timer_10_select 0xf07a
#define MATSYM_timer_3 0xe424
#define MATSYM_timer_3_select 0xf07b
#define MATSYM_timer_off 0xe426
#define MATSYM_tips_and_updates 0xe79a
#define MATSYM_tire_repair 0xebc8
#define MATSYM_title 0xe264
#define MATSYM_toc 0xe8de
#define MATSYM_today 0xe8df
#define MATSYM_toggle_off 0xe9f5
#define MATSYM_toggle_on 0xe9f6
#define MATSYM_token 0xea25
#define MATSYM_toll 0xe8e0
#define MATSYM_tonality 0xe427
#define MATSYM_topic 0xf1c8
#define MATSYM_tornado 0xe199
#define MATSYM_touch_app 0xe913
#define MATSYM_tour 0xef75
#define MATSYM_toys 0xe332
#define MATSYM_track_changes 0xe8e1
#define MATSYM_traffic 0xe565
#define MATSYM_train 0xe570
#define MATSYM_tram 0xe571
#define MATSYM_transcribe 0xf8ec
#define MATSYM_transfer_within_a_station 0xe572
#define MATSYM_transform 0xe428
#define MATSYM_transgender 0xe58d
#define MATSYM_transit_enterexit 0xe579
#define MATSYM_translate 0xe8e2
#define MATSYM_travel_explore 0xe2db
#define MATSYM_trending_down 0xe8e3
#define MATSYM_trending_flat 0xe8e4
#define MATSYM_trending_neutral 0xe8e4
#define MATSYM_trending_up 0xe8e5
#define MATSYM_trip_origin 0xe57b
#define MATSYM_trolley 0xf86b
#define MATSYM_troubleshoot 0xe1d2
#define MATSYM_try 0xf07c
#define MATSYM_tsunami 0xebd8
#define MATSYM_tty 0xf1aa
#define MATSYM_tune 0xe429
#define MATSYM_tungsten 0xf07d
#define MATSYM_turn_left 0xeba6
#define MATSYM_turn_right 0xebab
#define MATSYM_turn_sharp_left 0xeba7
#define MATSYM_turn_sharp_right 0xebaa
#define MATSYM_turn_slight_left 0xeba4
#define MATSYM_turn_slight_right 0xeb9a
#define MATSYM_turned_in 0xe8e6
#define MATSYM_turned_in_not 0xe8e7
#define MATSYM_tv 0xe333
#define MATSYM_tv_off 0xe647
#define MATSYM_two_wheeler 0xe9f9
#define MATSYM_type_specimen 0xf8f0
#define MATSYM_u_turn_left 0xeba1
#define MATSYM_u_turn_right 0xeba2
#define MATSYM_umbrella 0xf1ad
#define MATSYM_unarchive 0xe169
#define MATSYM_undo 0xe166
#define MATSYM_unfold_less 0xe5d6
#define MATSYM_unfold_less_double 0xf8cf
#define MATSYM_unfold_more 0xe5d7
#define MATSYM_unfold_more_double 0xf8d0
#define MATSYM_unpublished 0xf236
#define MATSYM_unsubscribe 0xe0eb
#define MATSYM_upcoming 0xf07e
#define MATSYM_update 0xe923
#define MATSYM_update_disabled 0xe075
#define MATSYM_upgrade 0xf0fb
#define MATSYM_upload 0xf09b
#define MATSYM_upload_file 0xe9fc
#define MATSYM_usb 0xe1e0
#define MATSYM_usb_off 0xe4fa
#define MATSYM_vaccines 0xe138
#define MATSYM_vape_free 0xebc6
#define MATSYM_vaping_rooms 0xebcf
#define MATSYM_verified 0xef76
#define MATSYM_verified_user 0xe8e8
#define MATSYM_vertical_align_bottom 0xe258
#define MATSYM_vertical_align_center 0xe259
#define MATSYM_vertical_align_top 0xe25a
#define MATSYM_vertical_distribute 0xe076
#define MATSYM_vertical_shades 0xec0e
#define MATSYM_vertical_shades_closed 0xec0d
#define MATSYM_vertical_split 0xe949
#define MATSYM_vibration 0xe62d
#define MATSYM_video_call 0xe070
#define MATSYM_video_camera_back 0xf07f
#define MATSYM_video_camera_front 0xf080
#define MATSYM_video_chat 0xf8a0
#define MATSYM_video_collection 0xe04a
#define MATSYM_video_file 0xeb87
#define MATSYM_video_label 0xe071
#define MATSYM_video_library 0xe04a
#define MATSYM_video_settings 0xea75
#define MATSYM_video_stable 0xf081
#define MATSYM_videocam 0xe04b
#define MATSYM_videocam_off 0xe04c
#define MATSYM_videogame_asset 0xe338
#define MATSYM_videogame_asset_off 0xe500
#define MATSYM_view_agenda 0xe8e9
#define MATSYM_view_array 0xe8ea
#define MATSYM_view_carousel 0xe8eb
#define MATSYM_view_column 0xe8ec
#define MATSYM_view_comfortable 0xe42a
#define MATSYM_view_comfy 0xe42a
#define MATSYM_view_comfy_alt 0xeb73
#define MATSYM_view_compact 0xe42b
#define MATSYM_view_compact_alt 0xeb74
#define MATSYM_view_cozy 0xeb75
#define MATSYM_view_day 0xe8ed
#define MATSYM_view_headline 0xe8ee
#define MATSYM_view_in_ar 0xe9fe
#define MATSYM_view_kanban 0xeb7f
#define MATSYM_view_list 0xe8ef
#define MATSYM_view_module 0xe8f0
#define MATSYM_view_quilt 0xe8f1
#define MATSYM_view_sidebar 0xf114
#define MATSYM_view_stream 0xe8f2
#define MATSYM_view_timeline 0xeb85
#define MATSYM_view_week 0xe8f3
#define MATSYM_vignette 0xe435
#define MATSYM_villa 0xe586
#define MATSYM_visibility 0xe8f4
#define MATSYM_visibility_off 0xe8f5
#define MATSYM_voice_chat 0xe62e
#define MATSYM_voice_over_off 0xe94a
#define MATSYM_voicemail 0xe0d9
#define MATSYM_volcano 0xebda
#define MATSYM_volume_down 0xe04d
#define MATSYM_volume_down_alt 0xe79c
#define MATSYM_volume_mute 0xe04e
#define MATSYM_volume_off 0xe04f
#define MATSYM_volume_up 0xe050
#define MATSYM_volunteer_activism 0xea70
#define MATSYM_vpn_key 0xe0da
#define MATSYM_vpn_key_off 0xeb7a
#define MATSYM_vpn_lock 0xe62f
#define MATSYM_vrpano 0xf082
#define MATSYM_wallet 0xf8ff
#define MATSYM_wallet_giftcard 0xe8f6
#define MATSYM_wallet_membership 0xe8f7
#define MATSYM_wallet_travel 0xe8f8
#define MATSYM_wallpaper 0xe1bc
#define MATSYM_warehouse 0xebb8
#define MATSYM_warning 0xe002
#define MATSYM_warning_amber 0xf083
#define MATSYM_wash 0xf1b1
#define MATSYM_watch 0xe334
#define MATSYM_watch_later 0xe924
#define MATSYM_watch_off 0xeae3
#define MATSYM_water 0xf084
#define MATSYM_water_damage 0xf203
#define MATSYM_water_drop 0xe798
#define MATSYM_waterfall_chart 0xea00
#define MATSYM_waves 0xe176
#define MATSYM_waving_hand 0xe766
#define MATSYM_wb_auto 0xe42c
#define MATSYM_wb_cloudy 0xe42d
#define MATSYM_wb_incandescent 0xe42e
#define MATSYM_wb_iridescent 0xe436
#define MATSYM_wb_shade 0xea01
#define MATSYM_wb_sunny 0xe430
#define MATSYM_wb_twighlight 0xea02
#define MATSYM_wb_twilight 0xe1c6
#define MATSYM_wc 0xe63d
#define MATSYM_web 0xe051
#define MATSYM_web_asset 0xe069
#define MATSYM_web_asset_off 0xe4f7
#define MATSYM_web_stories 0xe595
#define MATSYM_webhook 0xeb92
#define MATSYM_wechat 0xea81
#define MATSYM_weekend 0xe16b
#define MATSYM_west 0xf1e6
#define MATSYM_whatshot 0xe80e
#define MATSYM_wheelchair_pickup 0xf1ab
#define MATSYM_where_to_vote 0xe177
#define MATSYM_widgets 0xe1bd
#define MATSYM_width_full 0xf8f5
#define MATSYM_width_normal 0xf8f6
#define MATSYM_width_wide 0xf8f7
#define MATSYM_wifi 0xe63e
#define MATSYM_wifi_1_bar 0xe4ca
#define MATSYM_wifi_2_bar 0xe4d9
#define MATSYM_wifi_calling 0xef77
#define MATSYM_wifi_calling_3 0xf085
#define MATSYM_wifi_channel 0xeb6a
#define MATSYM_wifi_find 0xeb31
#define MATSYM_wifi_lock 0xe1e1
#define MATSYM_wifi_off 0xe648
#define MATSYM_wifi_password 0xeb6b
#define MATSYM_wifi_protected_setup 0xf0fc
#define MATSYM_wifi_tethering 0xe1e2
#define MATSYM_wifi_tethering_error 0xead9
#define MATSYM_wifi_tethering_error_rounded 0xf086
#define MATSYM_wifi_tethering_off 0xf087
#define MATSYM_wind_power 0xec0c
#define MATSYM_window 0xf088
#define MATSYM_wine_bar 0xf1e8
#define MATSYM_woman 0xe13e
#define MATSYM_woman_2 0xf8e7
#define MATSYM_woo_commerce 0xea6d
#define MATSYM_wordpress 0xea9f
#define MATSYM_work 0xe8f9
#define MATSYM_work_history 0xec09
#define MATSYM_work_off 0xe942
#define MATSYM_work_outline 0xe943
#define MATSYM_workspace_premium 0xe7af
#define MATSYM_workspaces 0xe1a0
#define MATSYM_workspaces_filled 0xea0d
#define MATSYM_workspaces_outline 0xea0f
#define MATSYM_wrap_text 0xe25b
#define MATSYM_wrong_location 0xef78
#define MATSYM_wysiwyg 0xf1c3
#define MATSYM_yard 0xf089
#define MATSYM_youtube_searched_for 0xe8fa
#define MATSYM_zoom_in 0xe8ff
#define MATSYM_zoom_in_map 0xeb2d
#define MATSYM_zoom_out 0xe900
#define MATSYM_zoom_out_map 0xe56b
