// ReSharper disable once CppMissingIncludeGuard
#define GERBER_ERROR_CODES                          \
    GERBER_ERROR_CODE(unspecified)                  \
    GERBER_ERROR_CODE(out_of_range)                 \
    GERBER_ERROR_CODE(not_supported)                \
    GERBER_ERROR_CODE(missing_integer_value)        \
    GERBER_ERROR_CODE(missing_real_number_value)    \
    GERBER_ERROR_CODE(malformed_integer)            \
    GERBER_ERROR_CODE(malformed_real_number)        \
    GERBER_ERROR_CODE(unexpected_input)             \
    GERBER_ERROR_CODE(undefined_d_code)             \
    GERBER_ERROR_CODE(bad_parameter_index)          \
    GERBER_ERROR_CODE(bad_parameter_count)          \
    GERBER_ERROR_CODE(bad_aperture_number)          \
    GERBER_ERROR_CODE(unexpected_code)              \
    GERBER_ERROR_CODE(unknown_code)                 \
    GERBER_ERROR_CODE(unknown_aperture_macro)       \
    GERBER_ERROR_CODE(invalid_code)                 \
    GERBER_ERROR_CODE(cant_open_file)               \
    GERBER_ERROR_CODE(unexpected_eof)               \
    GERBER_ERROR_CODE(missing_command)              \
    GERBER_ERROR_CODE(malformed_command)            \
    GERBER_ERROR_CODE(excessive_macro_parameters)   \
    GERBER_ERROR_CODE(unknown_command)              \
    GERBER_ERROR_CODE(invalid_number)               \
    GERBER_ERROR_CODE(invalid_axis)                 \
    GERBER_ERROR_CODE(invalid_aperture_type)        \
    GERBER_ERROR_CODE(invalid_omit_zeros)           \
    GERBER_ERROR_CODE(invalid_coordinate_setting)   \
    GERBER_ERROR_CODE(invalid_format_specification) \
    GERBER_ERROR_CODE(invalid_axis_select)          \
    GERBER_ERROR_CODE(invalid_mirror_state)         \
    GERBER_ERROR_CODE(invalid_mode)                 \
    GERBER_ERROR_CODE(invalid_offset)               \
    GERBER_ERROR_CODE(invalid_polarity)             \
    GERBER_ERROR_CODE(invalid_level_polarity)       \
    GERBER_ERROR_CODE(invalid_knockout_polarity)    \
    GERBER_ERROR_CODE(invalid_step_and_repeat)      \
    GERBER_ERROR_CODE(invalid_knockout_variable)    \
    GERBER_ERROR_CODE(invalid_rotation)             \
    GERBER_ERROR_CODE(invalid_aperture_definition)  \
    GERBER_ERROR_CODE(end_of_file)                  \
    GERBER_ERROR_CODE(insufficent_data)             \
    GERBER_ERROR_CODE(missing_terminator)           \
    GERBER_ERROR_CODE(invalid_arc)                  \
    GERBER_ERROR_CODE(internal_bad_pointer)         \
    GERBER_ERROR_CODE(internal_bad_argument)        \
    GERBER_ERROR_CODE(unterminated_command)         \
    GERBER_ERROR_CODE(invalid_interpolation)        \
    GERBER_ERROR_CODE(invalid_file_attributes)      \
    GERBER_ERROR_CODE(duplicate_aperture_number)    \
    GERBER_ERROR_CODE(bad_outline_points_data)      \
    GERBER_ERROR_CODE(unsupported_command)          \
    GERBER_ERROR_CODE(invalid_primitive_number)     \
    GERBER_ERROR_CODE(mismatched_brackets)          \
    GERBER_ERROR_CODE(formula_too_complex)          \
    GERBER_ERROR_CODE(bad_macro_name)               \
    GERBER_ERROR_CODE(expression_stack_underflow)   \
    GERBER_ERROR_CODE(invalid_aperture_macro)       \
    GERBER_ERROR_CODE(syntax_error)                 \
    GERBER_ERROR_CODE(empty_file)                   \
    GERBER_ERROR_CODE(bad_file_offset)              \
    GERBER_ERROR_CODE(file_not_found)               \
    GERBER_ERROR_CODE(missing_attribute)            \
    GERBER_ERROR_CODE(invalid_parameter)
